### ISSUE TITLE
FPGA: ICCM corruption while writing FMC

### ISSUE THREAD

**Issue by jlmahowa-amd** [chipsalliance/caliptra-rtl#100]
On FPGA corruption is observed in the ICCM. The data read back from ICCM is not what was intended to be written.
FPGA based on: d334c84a0e513a3d66a51078f020a414a2c86a67

FMC execution:
![image](https://github.com/chipsalliance/caliptra-rtl/assets/102375203/17f6ae75-4d94-436b-b5a6-ba3fc34a9516)
FMC fetch from 0x1a8 is 0x82930000.

FMC load:
![image](https://github.com/chipsalliance/caliptra-rtl/assets/102375203/4bedadc8-0628-4902-891d-81d842542c93)
ROM attempts to write 0x35170053 to ICCM. One clock later 0x82930000 is on the iccm_wr_data.

ICCM might not be correctly latching the iccm_wr_data in time before iccm_wr_data changes.
FPGA specific concerns:
- ICCM is implemented on FPGA using a block memory.
- There are no timing failures, but FPGA timing might be an issue.

**Comment by korran** [comment]
Which RTL commit was this built from?

**Comment by fdamato** [comment]
https://github.com/chipsalliance/caliptra-rtl/commit/d334c84a0e513a3d66a51078f020a414a2c86a67

**Comment by jlmahowa-amd** [comment]
FW commit is with e1b1e3c566b6bd7cdef0310dc88480034f0aa29f with modifications to the FPGA hw-model.

I'm trying to investigate the FPGA paths. Caliptra is clocked so slowly it is hard to believe there would be timing issues.

**Comment by jlmahowa-amd** [comment]
Uploaded changes to GitHub.
https://github.com/chipsalliance/caliptra-sw/tree/jlmahowa/fpga-hw-model
https://github.com/chipsalliance/caliptra-rtl/tree/caliptra-sw-based-fpga

**Comment by jlmahowa-amd** [comment]
Rebasing SW repo to 8e5e385abb8e3e7d19cc613a036994fbd5018306 changes the ROM/FMC and the behavior with the same FPGA image changes slightly. ICCM address 0x8854 is fetched one cycle before 0x854. Suspecting that the extra bit set in the address is unintended and that the core chokes on the garbage data at 0x8854.
![image](https://github.com/chipsalliance/caliptra-rtl/assets/102375203/bd7c7b17-7ed3-4394-808d-e888d3a05439)

**Comment by bharatpillilli** [comment]
Not a RTL issue
