### ISSUE TITLE
Increase ROM max. supported size to 48 KBytes

### ISSUE THREAD

**Issue by mhatrevi** [chipsalliance/caliptra-rtl#101]
Justification: Currently, the ROM is cutting close to its max. limit of 32 KB; we need to increase the ROM size to incorporate additional ROM features. Some of these features, such as Control Flow integrity checks, are critical from a security standpoint. Increasing the ROM max. size to 48 KB would enable implementing these new features.

**Comment by mhatrevi** [comment]
Adding approval related questionnaire:

• Is the RTL change due to a Spec change? Yes

• Is the Spec change approved? No

• Is the spec updated? No

• Is the change needed in Caliptra 0p8 or 1p0 milestone? 1p0

• Note: What item qualifies as P1/MVP item is set by Caliptra Arch WG leads

• Does it have silicon area impact? Yes – ~5000umm2 (but 48KB denomination may not be available => it could be greater than that for some processes?)

• Does it have timing impact? No

• If the change impacts ROM/FMC/RT, did the FW reps approve the change already? Yes

• Why should the change be intercepted in Gen 1? -> See justifications/description by the owner

• Can the change be handled outside of Caliptra? No

• If there is a schedule impact to Caliptra 0p8 or 1p0 milestone, is it approved by voting leads? à TBD

• If change completed (implies schedule impact is zero): à NA

• Lint passing – Yes/No

• Gate count delta – NA (see area impact)

• Tests written for testing the change – Yes/No

• Tests checked-in for this change

• Existing smoke tests passing? – Yes/No

**Comment by calebofearth** [comment]
This change is completed in the Microsoft internal repo and will be merged to dev-msft in the next sync.
