### ISSUE TITLE
Skip clock gating tests in Verilator regression

### ISSUE THREAD

**Issue by upadhyayulakiran** [chipsalliance/caliptra-rtl#126]
L0 regression test list will soon include (next sync) the following clock gating tests:
1. smoke_test_clk_gating
2. smoke_test_cg_wdt

These need to be **excluded** from the Verilator regression due to an outstanding issue with Verilator to avoid hangs - filed here:
[https://github.com/chipsalliance/Cores-VeeR-EL2/issues/88](url)

**Comment by calebofearth** [comment]
@mkurc-ant Do you have some bandwidth to help add this exclusion to our workflows?

**Comment by mkurc-ant** [comment]
@calebofearth Sure, I'll take look into it. Though I can't find the `smoke_test_clk_gating` test to be disabled anywhere in `src/integration/test_suites` (https://github.com/chipsalliance/caliptra-rtl/tree/main/src/integration/test_suites)

**Comment by calebofearth** [comment]
Thanks! These tests were recently added in the MSFT internal repository and will be sync'ed to GitHub in the next several days. We're hoping that adding an exception for the test names will prevent things from breaking once that sync goes through.
