### ISSUE TITLE
Undriven nets may cause issues for Formal LEC flows

### ISSUE THREAD

**Issue by nstewart-amd** [chipsalliance/caliptra-rtl#128]
The following nets are deemed undriven in formal equivalency check flows.
If integrators use binary:X modelling for undriven nets, these will result in equivalency check failures.
Recommend TIE0 or tie to valid logic.

**************************************************
Report         : undriven_nets

Reference      : r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper
Implementation : i:/FMWORK_IMPL_CALIPTRA_WRAPPER/caliptra_wrapper
Version        : S-2021.06-SP2
Date           : Thu Jun 15 00:04:28 2023
**************************************************

73 Undriven nets:

r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[41]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_eccerr[0]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_eccerr[1]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[69]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[57]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[15]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[18]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[1]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[11]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[60]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[0]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[67]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[51]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[61]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[34]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[39]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[53]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[16]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[58]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[64]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[17]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[2]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[12]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[62]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[54]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[56]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[68]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[66]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[52]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[19]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[65]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[44]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[59]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[70]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[29]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[55]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[7]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[63]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[46]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[26]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[33]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[35]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[36]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[37]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[38]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[25]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[40]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[10]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[9]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[42]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[32]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[31]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[43]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[47]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[48]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[49]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[50]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[30]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[24]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[23]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[8]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[28]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[27]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[22]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[21]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[14]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[13]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[6]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[20]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[4]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[3]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[45]
r:/FMWORK_REF_CALIPTRA_WRAPPER/caliptra_wrapper/caliptra_top/rvtop/mem/ic_debug_rd_data[5]

**Comment by bharatpillilli** [comment]
All/most of these signals are from rv top. So assigning to Karol
