### ISSUE TITLE
SHA Accelerator Parameter Checking

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-rtl#135]
SHA Accelerated will verify that the parameters to the accelerator were correctly formed.

**Comment by JohnTraverAmd** [comment]
We will need to look at all the parameters and see how this may not already be completed.

**Comment by bharatpillilli** [comment]
Is it a question, enhancement or a bug? The HW design document specifies the sha512 crypto itself and shacc arch registers in SOC IFC provide the registers/configurations exposed.

**Comment by bharatpillilli** [comment]
Is there any work associated with this? @JohnTraverAmd

**Comment by JohnTraverAmd** [comment]
@bharatpillilli can you list what enforcements the HW makes?  For example, What happens if the command size is beyond what is valid in the mb?

**Comment by bharatpillilli** [comment]
Hi @JohnTraverAmd - SOC can only use streaming mode (means size of the image doesnt matter as its getting streamed and hash is calculated as the data is being streamed)...they cant use mailbox mode directly...using mailbox mode for SHA is a FW API, and there is no HW involvement
