### ISSUE TITLE
Document TRNG REQ HW API timing requirements

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-rtl#136]
In [Caliptra_Integration_Specification.pdf](https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/Caliptra_Integration_Specification.pdf), section 8 (TRNG REQ HW API) doesn't mention timing requirements at all. These need to be documented explicitly.

We need to know the upper bound on how long this operation can take in order to set watchdog timeouts correctly.

**Comment by FerralCoder** [comment]
Kor Nielsen (Google)
  [7 minutes ago]
Now that the watchdog is configured externally this isn't as important.
However, we probably need to document the hard coded timeout for etrng requests. Constant is here: https://github.com/chipsalliance/caliptra-sw/blob/df44c09aab24fc72010cce83507cbab1c9e04928/drivers/src/trng_ext.rs#L18

        const MAX_CYCLES_TO_WAIT: u32 = 250000;
