### ISSUE TITLE
How is FMC's alias key and CDI unlocked for use upon hitless update?

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-rtl#138]
FMC uses its CDI to derive the RT FW alias key + RT FW CDI, and uses FMC's alias key to endorse RT FW's alias key. Before jumping to RT FW, FMC should ensure that its CDI and alias key are inaccessible to FW.

Upon hitless update, FMC runs again and needs to wield its CDI and alias key to derive a new DICE identity for the new RT FW.

How does hardware do this? Are the usage lock bits reset? For all KV slots or specific ones?

**Comment by varuns-nvidia** [comment]
IIRC the lock bits are on cptra_rst_b (microcontroller reset) but the key vault entries are on the cptra_pwrgood reset. It's up to ROM and FMC to re-lock entries on hitless update.

**Comment by bluegate010** [comment]
From Bharat: "All slots get unlocked and each layer is responsible for locking the keys it programmed."
