### ISSUE TITLE
Paths need to be adjusted

### ISSUE THREAD

**Issue by steven-bellock** [chipsalliance/caliptra-rtl#14]
It seems like before this repository went public it was called `Caliptra`? Now it's called `caliptra-rtl` and the .vf files and scripts and makefiles need to be updated. For example https://github.com/chipsalliance/caliptra-rtl/blob/01fcfd15c6caf75d62a0cf4423605ffa3691fb2a/src/pcrvault/config/pcrvault.vf#L4-L6

**Comment by calebofearth** [comment]
Please refer to PR #21
