### ISSUE TITLE
Security_state multi-driver in caliptra_top_tb

### ISSUE THREAD

**Issue by calebofearth** [chipsalliance/caliptra-rtl#147]
After merging the latest changes to the MSFT internal repo I hit a multi-driver on the security_state signal in caliptra_top_tb. The signal is driven out of caliptra_top_tb_services, and PR #72 also adds a driver inside caliptra_top_tb for this signal. 

@mkurc-ant do you recall what issue you were hitting that made this second driver necessary?

Really cool PR btw, thanks for getting it in.

**Comment by calebofearth** [comment]
There was a stale FIXME in the code, maybe that was just a red herring.

For now I'm just removing the new code in caliptra_top_tb and moving that ifdef around the `initial` block inside caliptra_top_tb_services. This should be merged back to this repo soon.
LMK if you're aware of any other gotchas associated with this change.

**Comment by mkurc-ant** [comment]
@calebofearth I had to set `debug_locked` to 0 for JTAG to work. It looks like when I initially began working on that either `security_state` wasn't driven from `caliptra_top_tb_services` or I just overlooked it.

Anyways, CI JTAG tests rely on the `CALIPTRA_DEBUG_UNLOCKED` define. If `security_state` is to be driven elsewhere in the testbench it should honor the define.

**Comment by calebofearth** [comment]
Alright, thanks for the info. I will keep the CALIPTRA_DEBUG_UNLOCKED behavior in place in the forthcoming fix.

**Comment by calebofearth** [comment]
Fix was merged to main in https://github.com/chipsalliance/caliptra-rtl/pull/154 (commit https://github.com/chipsalliance/caliptra-rtl/commit/807de2b19b9a799e1063bdd3b96fcf480f473017 specifically).

**Comment by calebofearth** [comment]
Looks like the fix didn't make it through in #148 , due to some merge conflict resolution issue.

The fix is brought in manually with PR #158 .
