### ISSUE TITLE
`WORKSPACE` collision

### ISSUE THREAD

**Issue by steven-bellock** [chipsalliance/caliptra-rtl#15]
I (and maybe others) already have `WORKSPACE` defined. (In my case it's for [Perforce](https://www.perforce.com/manuals/p4v/Content/P4V/using.workspaces.html)). Can this be renamed to (something like) `CALIPTRA_WORKSPACE`?

**Comment by calebofearth** [comment]
Please take a look at PR #21, with a fix for this issue.
