### ISSUE TITLE
program.hex image generation is not successful for caliptra_demo caliptra_rt caliptra fmc

### ISSUE THREAD

**Issue by dayanajayaraman** [chipsalliance/caliptra-rtl#156]
Hi,

While trying to generate program.hex for caliptra_demo caliptra_rt and caliptra_fmc error message is flagged.

caliptra_rt, caliptra_fmc 
error: ld returned 1 

caliptra_demo.c error: 'CLP_KV_REG_PCR_ENTRY_0_0' undeclared (first use in this function); did you mean 'CLP_PV_REG_PCR_ENTRY_0_0'? 131 \| reg_ptr = (uint32_t*) CLP_KV_REG_PCR_ENTRY_0_0; \| ^~~~~~~~~~~~~~~~~~~~~~~~ \| CLP_PV_REG_PCR_ENTRY_0_0 caliptra_demo.c:131:27: note: each undeclared identifier is reported only once for each function it appears in 

caliptra_demo.c:139:67: error: 'HMAC_REG_HMAC384_KV_RD_KEY_CTRL_ENTRY_IS_PCR_MASK' undeclared (first use in this function); did you mean 'HMAC_REG_HMAC384_KV_RD_KEY_CTRL_RSVD_MASK'? 139 \| HMAC_REG_HMAC384_KV_RD_KEY_CTRL_ENTRY_IS_PCR_MASK \| \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \| HMAC_REG_HMAC384_KV_RD_KEY_CTRL_RSVD_MASK 

caliptra_demo.c:140:75: error: 'HMAC_REG_HMAC384_KV_RD_KEY_CTRL_ENTRY_DATA_SIZE_LOW' undeclared (first use in this function); did you mean 'HMAC_REG_HMAC384_KV_RD_KEY_CTRL_PCR_HASH_EXTEND_LOW'? 140 \| (0xB << HMAC_REG_HMAC384_KV_RD_KEY_CTRL_ENTRY_DATA_SIZE_LOW)); \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \| HMAC_REG_HMAC384_KV_RD_KEY_CTRL_PCR_HASH_EXTEND_LOW 

caliptra_demo.c:147:77: error: 'HMAC_REG_HMAC384_KV_RD_BLOCK_CTRL_ENTRY_DATA_SIZE_LOW' undeclared (first use in this function); did you mean 'HMAC_REG_HMAC384_KV_RD_BLOCK_CTRL_PCR_HASH_EXTEND_LOW'? 147 \| (0xB << HMAC_REG_HMAC384_KV_RD_BLOCK_CTRL_ENTRY_DATA_SIZE_LOW)); \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \| HMAC_REG_HMAC384_KV_RD_BLOCK_CTRL_PCR_HASH_EXTEND_LOW 

caliptra_demo.c: In function 'ldevid': 
caliptra_demo.c:210:75: error: 'HMAC_REG_HMAC384_KV_RD_KEY_CTRL_ENTRY_DATA_SIZE_LOW' undeclared (first use in this function); did you mean 'HMAC_REG_HMAC384_KV_RD_KEY_CTRL_PCR_HASH_EXTEND_LOW'? 210 \| (0xB << HMAC_REG_HMAC384_KV_RD_KEY_CTRL_ENTRY_DATA_SIZE_LOW)); \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \| HMAC_REG_HMAC384_KV_RD_KEY_CTRL_PCR_HASH_EXTEND_LOW 

caliptra_demo.c:218:78: error: 'HMAC_REG_HMAC384_KV_RD_BLOCK_CTRL_ENTRY_DATA_SIZE_LOW' undeclared (first use in this function); did you mean 'HMAC_REG_HMAC384_KV_RD_BLOCK_CTRL_PCR_HASH_EXTEND_LOW'? 218 \| (0x1F << HMAC_REG_HMAC384_KV_RD_BLOCK_CTRL_ENTRY_DATA_SIZE_LOW)); \| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \|
--

**Comment by calebofearth** [comment]
caliptra_demo.c is not included in our L0 regression test suite and is not regularly maintained.
caliptra_rt, caliptra_fmc are simple facsimiles of the "Runtime" and "FMC" firmware, designed to support the UVM regression flow. They won't be useful for standalone caliptra_top_tb tests.

**Comment by calebofearth** [comment]
@dayanajayaraman can we close this issue?
