### ISSUE TITLE
Reserve RW bit in CPTRA_FLOW_STATUS for idevid_csr_ready

### ISSUE THREAD

**Issue by jlmahowa-amd** [chipsalliance/caliptra-rtl#157]
"PR 113668: RDC clock gating fix for warm reset and masking for…" changed the definition of CPTRA_FLOW_STATUS. FW was using bit 27 for idevid_csr_ready. After this change 27:25 is no longer writable with FW. Reserving a bit in this register for idevid_csr_ready in the RDL would prevent conflicts like this in the future. Currently I am changing the FW to use bit 24 to make progress.

**Comment by korran** [comment]
Can we register bit 24 in the RDL as writable by firmware, with the name "idevid_csr_ready"?

**Comment by calebofearth** [comment]
We don't have any further changes to this register pending on the HW side, so using bit 24 is safe for now.
I can try to get in a fix for this next week.

**Comment by bharatpillilli** [comment]
To ensure we dont have these conflicts, we should ensure any bits that are being used by FW are updated in the RDL appropriately @jlmahowa-amd @korran - in future, we should file an issue.

**Comment by bharatpillilli** [comment]
@upadhyayulakiran - lets combine this with the other register fix that you might have to make today.

**Comment by bharatpillilli** [comment]
Marking approved as its a rdl impact and has no other impacts (RTL is there, val is there for checking read/write checks etc.)

**Comment by upadhyayulakiran** [comment]
This change is merged to main. Closing work item
