### ISSUE TITLE
CPTRA_FLOW_STATUS.ready_for_runtime bit description is inaccurate in RDL file

### ISSUE THREAD

**Issue by calebofearth** [chipsalliance/caliptra-rtl#160]
Description in the RDL file does not match the (correct) description in the Caliptra Integration Specification.

**Comment by bharatpillilli** [comment]
@upadhyayulakiran - lets combine this with the other register fix that you might have to make today.
@calebofearth can provide the details

**Comment by calebofearth** [comment]
@upadhyayulakiran I forwarded the discussion email to you for context about this issue.

**Comment by upadhyayulakiran** [comment]
Fixed the description
