### ISSUE TITLE
Do not clear non-sticky registers on a Warm Reset

### ISSUE THREAD

**Issue by mhatrevi** [chipsalliance/caliptra-rtl#161]
Justification: Currently, NONSTICKY_DATA_VAULT_ENTRY, NonStickyLockableScratchReg and NonStickyGenericScratchReg registers are unlocked and cleared on a Warm Reset. On a Cold Boot, ROM stores information such as the RT Load Address and Entry point in these registers. On a Warm Reset, since these registers are cleared, FMC does not have the RT Entry point and is unable to transfer the execution to it. 

The desired behavior would be to not clear these registers and only unlock them.

Note: Unlocking is needed so that the ROM can update these registers in case of a hitless update.

**Comment by mhatrevi** [comment]
Adding approval related questionnaire:

• Is the RTL change due to a Spec change? No

• Is the Spec change approved? NA

• Is the spec updated? NA

• Is the change needed in Caliptra 0p8 or 1p0 milestone? 1p0

• Note: What item qualifies as P1/MVP item is set by Caliptra Arch WG leads

• Does it have silicon area impact? No

• Does it have timing impact? No

• If the change impacts ROM/FMC/RT, did the FW reps approve the change already? Yes

• Why should the change be intercepted in Gen 1? -> See justifications/description by the owner

• Can the change be handled outside of Caliptra? No

• If there is a schedule impact to Caliptra 0p8 or 1p0 milestone, is it approved by voting leads? à TBD

• If change completed (implies schedule impact is zero): à NA

• Lint passing – Yes/No

• Gate count delta – NA (see area impact)

• Tests written for testing the change – Yes/No

• Tests checked-in for this change

• Existing smoke tests passing? – Yes/No

**Comment by upadhyayulakiran** [comment]
From offline discussion, NonStickyGenericScratchReg are still nonsticky and clear on warm reset. NONSTICKY_DATA_VAULT_ENTRY, NonStickyLockableScratchReg have been changed to be only unlocked and not be cleared on warm reset
