### ISSUE TITLE
Add tests for JTAG accesses with clock gating enabled

### ISSUE THREAD

**Issue by upadhyayulakiran** [chipsalliance/caliptra-rtl#162]
JTAG access when clock gating is enabled and core is halted may have an issue. The mailbox read pointer increments but since mailbox is on gated clock, it will miss the update. We will fix it by waking up clocks during JTAG accesses, but filing this as a FYI so we can add some tests to cover this case. 

![image](https://github.com/chipsalliance/caliptra-rtl/assets/125604693/052bbc57-8a10-40fc-9148-7d8f4292de7e)

**Comment by bharatpillilli** [comment]
@kgugala - can we plz ensure that this test case is covered as we found a bug on JTAG+Clk gating interaction?

**Comment by bharatpillilli** [comment]
@kgugala - any update?

**Comment by tmichalak** [comment]
Okay, I noticed that it is part of [this commit](https://github.com/chipsalliance/caliptra-rtl/commit/b436906f0b16ae0cfbb160e927499b79800ec9ce), correct?

**Comment by upadhyayulakiran** [comment]
Summarizing conversation from issue #197, JTAG can only be enabled in debug mode where clocks are always on by design. So, adding a test to do JTAG access with clock gating enabled is not possible. It's still good to check that when the clock gating enable reg is set and debug mode is enabled for JTAG accesses, clocks are active. Closing this issue.
