### ISSUE TITLE
Exercising block level tb

### ISSUE THREAD

**Issue by dayanajayaraman** [chipsalliance/caliptra-rtl#163]
While exercising below block level test benches in VCS facing simulation hang /run for long time , updated file list from config path
Is any inputs files needs to be added/updated?
ECC, CSR,DOE, soc_ifc

**Comment by dayanajayaraman** [comment]
Not able to run ECC block/ip test can you please share the steps?

**Comment by calebofearth** [comment]
To run ECC block testbench:
1. Compile the testbench source using [ecc_top_tb.vf](https://github.com/chipsalliance/caliptra-rtl/blob/main/src/ecc/config/ecc_top_tb.vf)
1. In the output/run folder, execute `cp $CALIPTRA_ROOT/src/ecc/tb/test_vectors/mm_test_vectors*.hex .` as shown [here](https://github.com/chipsalliance/caliptra-rtl/blob/63ad025d1f796198386dd38aec5c17c12f5b24f6/src/ecc/config/compile.yml#L74)
1. Execute the sim. Depending on which test you intend to run, provide the necessary plusargs. Plusargs to use are defined for each test [here](https://github.com/chipsalliance/caliptra-rtl/tree/main/src/ecc/stimulus/tests/directed)
