### ISSUE TITLE
Caliptra RTL does not contains SDC Constraints provided 

### ISSUE THREAD

**Issue by saidheeraj111** [chipsalliance/caliptra-rtl#169]
Hi Bharat and team,
                                Can you please provide the SDC Constraint file which can be delivered by IP which can be used for running Synthesis. The SDC Constraints requires needs to be include clock, reset, IO , multicycle and false path constraints required for the RTL which is available.

Thanks,
K. Dheeraj.

**Comment by saidheeraj111** [comment]
Hi Bharat and team,
                                   Can you provide the information related to SDC Constraint file for IP on immediate basis. I havent received any reply from last few days. I need this on urgent basis please help.

Thanks,
K. Dheeraj

**Comment by saidheeraj111** [comment]
Hi Stewart,
                 Can you help me providing SDC files for Caliptra IP delivered.

Thanks,
K. Dheeraj.

**Comment by syaxiado** [comment]
Hi,
We are also in need of SDC files for SOC integration.
Thanks.

**Comment by DerekWangScaleflux** [comment]
Hi,
     Any update one the SDC file ?
     And if SGDC file could be provided for CDC ?


Best Regards
Derek Wang

**Comment by Nitsirks** [comment]
@nstewart-amd is this something we can provide?

We don't have any complex constraints like MCP or false paths.

**Comment by nstewart-amd** [comment]
@Nitsirks -
I think this is per-integrator specific, and would be at the scope of the integrator wrapper.
We do not have Caliptra-only level constraints.
As above, there are no multicycle paths.
There is clock.
There is single cycle timing required between Caliptra IO and integrator wrapper logic.

**Comment by DerekWangScaleflux** [comment]
> @Nitsirks - I think this is per-integrator specific, and would be at the scope of the integrator wrapper. We do not have Caliptra-only level constraints. As above, there are no multicycle paths. There is clock. There is single cycle timing required between Caliptra IO and integrator wrapper logic.

Hi,
      Thanks for the reply.

      Could you help to clarify "There is single cycle timing required between Caliptra IO and integrator wrapper logic." ?
      Is it mentioned in the integration spec ?

Best Regards
Derek Wang

**Comment by nstewart-amd** [comment]
> > @Nitsirks - I think this is per-integrator specific, and would be at the scope of the integrator wrapper. We do not have Caliptra-only level constraints. As above, there are no multicycle paths. There is clock. There is single cycle timing required between Caliptra IO and integrator wrapper logic.
> 
> Hi, Thanks for the reply. Could you help to clarify "There is single cycle timing required between Caliptra IO and integrator wrapper logic." ? Is it mentioned in the integration spec ?
> 
> Best Regards Derek Wang

Derek - Please see section "Interfaces".  It describes the interfaces as synchronous/asynchronous.  Accordingly, all synchronous interfaces would be single cycle, synchronous.

Regards,
Norman
