### ISSUE TITLE
ECC: ecc_add_sub_mod_alter

### ISSUE THREAD

**Issue by ludwigatlubis** [chipsalliance/caliptra-rtl#173]
Hello, 

The block misses a case of modulo computation.
 
```
If a+b < prime -> ok
If a+b > prime && carry_over -> ok
If a+b > prime && !carry_over -> design returns a+b instead of a+b%p 
```

@mojtaba-bisheh provided a hot fix and it should be fixed with the code update. 

Hotfix: 
`assign res_o = sub_n ? (carry0_reg ^ carry1)? r1 : r0 : (carry0_reg) ? r0 : r1;`

**Comment by mojtaba-bisheh** [comment]
https://github.com/chipsalliance/caliptra-rtl/pull/172 sync to dev-msft should fix this
