### ISSUE TITLE
DFT issue: Scan Mux not present in the following reset path

### ISSUE THREAD

**Issue by saidheeraj111** [chipsalliance/caliptra-rtl#175]
Hi Bharat and Team,
                                  Can you please check this DFT issue observed during caliptra schematic debug using spyglass tool. I have already sent a mail to caliptra work group. Please find the below error snapshot where scan mux is missed.

Thanks,
K. Dheeraj
[Reset_path_issue.docx](https://github.com/chipsalliance/caliptra-rtl/files/12269564/Reset_path_issue.docx)

**Comment by saidheeraj111** [comment]
Hi Bharat,
                  Can you please let us know the fix as quickly as possible.

Thanks,
K. Dheeraj

**Comment by amullick40412** [comment]
Hi @bharatpillilli,

Looks like we would need DFT overrides on both _cptra_uc_rst_b_ and _cptra_noncore_rst_b_ before they are consumed.

caliptra_top.soc_ifc_top1.i_soc_ifc_boot_fsm.cptra_uc_rst_b 
caliptra_top.soc_ifc_top1.i_soc_ifc_boot_fsm.cptra_noncore_rst_b

I remember we had a discussion over DFT override logic inside veer core. However these resets are consumed by logic outside veer core as well and hence we should add the override logic inside Boot FSM before sending it out.

Regards,
Avirup

**Comment by saidheeraj111** [comment]
Hi Narasimha/Prasanna,
                                           The below mail is reply from the caliptra team. Seems they are talking about the DFT logic insertion. But they haven’t mentioned the date. So, based on this proceed further.


Thanks,
K. Dheeraj.

**Comment by saidheeraj111** [comment]
+ Rahul

From: Kakaraparthi Venkata siva sai Dheeraj ***@***.***>
Sent: Wednesday, August 16, 2023 10:00 AM
To: chipsalliance/caliptra-rtl ***@***.***>; chipsalliance/caliptra-rtl ***@***.***>
Cc: Author ***@***.***>; Katakam Narasimharao ***@***.***>; Prasanna Choudhary ***@***.***>
Subject: RE: [chipsalliance/caliptra-rtl] DFT issue: Scan Mux not present in the following reset path (Issue #175)

Hi Narasimha/Prasanna,
                                           The below mail is reply from the caliptra team. Seems they are talking about the DFT logic insertion. But they haven’t mentioned the date. So, based on this proceed further.


Thanks,
K. Dheeraj.

**Comment by Nitsirks** [comment]
Qualified generated resets with scan mode so that we don't incidentally reset flops during scan mode.

assign cptra_noncore_rst_b = cptra_noncore_rst_b_nq | scan_mode;
assign cptra_uc_rst_b = cptra_uc_rst_b_nq | scan_mode;
