### ISSUE TITLE
Add a new soc_ifc register for SOC integrators to provide a timeout for the ROM Watchdog Timer 

### ISSUE THREAD

**Issue by mhatrevi** [chipsalliance/caliptra-rtl#177]
This issue is for a new soc_ifc register request so that SOC integrators can provide a timeout value for the WDT. ROM will use this value to program the WDT. Unit of this register will be in cycles.

**Comment by mhatrevi** [comment]
Adding approval related questionnaire:

• Is the RTL change due to a Spec change? Yes

• Is the Spec change approved? No

• Is the spec updated? No

• Is the change needed in Caliptra 0p8 or 1p0 milestone? 1p0

• Note: What item qualifies as P1/MVP item is set by Caliptra Arch WG leads

• Does it have silicon area impact? Yes

• Does it have timing impact? No

• If the change impacts ROM/FMC/RT, did the FW reps approve the change already? Yes

• Why should the change be intercepted in Gen 1? -> See justifications/description by the owner

• Can the change be handled outside of Caliptra? No

• If there is a schedule impact to Caliptra 0p8 or 1p0 milestone, is it approved by voting leads? TBD

• If change completed (implies schedule impact is zero): NA

• Lint passing – Yes/No

• Gate count delta – NA (see area impact)

• Tests written for testing the change – Yes/No

• Tests checked-in for this change

• Existing smoke tests passing? – Yes/No

**Comment by Nitsirks** [comment]
New register is available.

reg {
    name = "Caliptra WDT1 Config";
    desc = "SOC provided count in cycles for WDT1 timeout.";
    field {sw=rw; hw=na; resetsignal = cptra_pwrgood;} TIMEOUT[32]=0;
 } CPTRA_WDT_CFG[2];
