### ISSUE TITLE
Package imports - Explicitly include dependencies, no implicit file read order of operations dependency

### ISSUE THREAD

**Issue by nstewart-amd** [chipsalliance/caliptra-rtl#182]
Caliptra RTL uses a series of SystemVerilog packages to wrap common code.
After enabling ITRNG, we are seeing some DCELAB issues where package content is being referenced in a module without a “import <pkg_name>::*” declaration first.

Explicit include files defining package dependencies and definitions.  Import the package before referencing it to avoid file-list ordering problems.

**Comment by calebofearth** [comment]
@howardtr can you take a look at this issue from TRNG?

**Comment by bharatpillilli** [comment]
@howardtr ?

**Comment by howardtr** [comment]
Hi @nstewart-amd 

1.  Can you send me a log of the errors that you're seeing? 
2. Are you using the [compile.yml](https://github.com/chipsalliance/caliptra-rtl/blob/dev-goog-integrate/src/csrng/config/compile.yml) files or the [.vf ](https://github.com/chipsalliance/caliptra-rtl/blob/dev-goog-integrate/src/csrng/config/csrng.vf)in the /config/ directories for the file list ordering?

**Comment by nstewart-amd** [comment]
Hi Howard,
I don't have log file readily available as we've corrected the issue locally.

Source file lists are frequently post-processed, and file order read-of-operations should not be assumed or guaranteed.

The error reported is effectively the same as reference to an undefined text macro, if that macro were included in .vh header which was not read prior to reference.

The standard coding practice request in this case is to explicitly included dependencies of any file before reference to those dependencies, hence removing dependency on file read order-of-operations assumptions in .vf list.

Regards,
Norman

**Comment by howardtr** [comment]
@nstewart-amd - do you have the corrected files that you can share with me so that I can understand and integrate into the codebase?  Thanks!

The current setup that we're using is based on the yml +.vf files, which is how OT did this as well.  Having said that, more than happy to accomodate changes required by the team

**Comment by nstewart-amd** [comment]
[caliptra_git_182.tar.gz](https://github.com/chipsalliance/caliptra-rtl/files/12579409/caliptra_git_182.tar.gz)

Attached reference file modifications in tarball.
Note that tick-includes have been added to files with implicit dependencies.

**Comment by bharatpillilli** [comment]
@howardtr - are we closing this?

**Comment by howardtr** [comment]
@bharatpillilli - I haven't had a chance to look at this, (competing priorities)

Giving myself a goal to get this lookedat/pushed by end of week

**Comment by bharatpillilli** [comment]
Any update @howardtr
