### ISSUE TITLE
{Security State, Device Life Cycle State[1:0]} documentation vs RTL mismatch

### ISSUE THREAD

**Issue by nstewart-amd** [chipsalliance/caliptra-rtl#184]
From the following document, https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#caliptra-security-states we see the Caliptra security state encoding as follows:

<html>
<body>

{Security State, Device Life Cycle State[1:0]} | State
-- | --
000b | DebugUnlocked and Unprovisioned
100b | DebugLocked and Manufacturing
101b | DebugLocked and Production
001b | DebugUnlocked and Production

</body>
</html>

However, looking at the RTL it appears to be below encoding.

<html>
<body>

{Security State, Device Life Cycle State[1:0]} | State
-- | --
000b | DebugUnlocked and Unprovisioned
101b | DebugLocked and Manufacturing
111b | DebugLocked and Production
011b | DebugUnlocked and Production

</body>
</html>

**Comment by bharatpillilli** [comment]
Mahmud filed a similar one on spec long time - not sure what happened with that. I will check with him too

**Comment by attzonko** [comment]
Confirmed with Anthony that ROM matches the encoding in RTL. So it sounds like we just need to update the spec.

**Comment by attzonko** [comment]
Here is the PR to fix it: https://github.com/chipsalliance/Caliptra/pull/135

**Comment by mahmud2023** [comment]
The concern I had originally was about the spec encoding of the lower two bits, **Device Lifecycle State[1:0]** -- does 00b indicate `Unprovisioned` or `Manufacturing`? 

The RTL does not have this contradiction. If the spec is updated to match the ROM and RTL, no further action is needed:
- 00b => `Unprovisioned` 
- 01b => `Manufacturing` 
- 11b => `Production`

**Comment by FerralCoder** [comment]
fixed in main spec https://github.com/chipsalliance/Caliptra/issues/19
