### ISSUE TITLE
coverage report for caliptra-rtl [block & integration]

### ISSUE THREAD

**Issue by dayanajayaraman** [chipsalliance/caliptra-rtl#189]
please share the coverage metrics[code coverage/functional coverage ]  report for caliptra-rtl.

Would like to analyze and add scenarios if required to achieve 100%,  as its one of the significant criteria to sign off RoT SS verification for our SoC.

**Comment by bharatpillilli** [comment]
We analyzed the functional coverage holes and anything relevant we have tests written

![image](https://github.com/chipsalliance/caliptra-rtl/assets/7234606/ddd7f676-52c7-452a-b29a-3cb4e09e737c)

**Comment by bharatpillilli** [comment]
Information provided
