### ISSUE TITLE
Add new SoC register(s) for integrators to configure entropy source health test thresholds

### ISSUE THREAD

**Issue by rkr35** [chipsalliance/caliptra-rtl#190]
## Health tests
The `entropy_src` peripheral receives bits from a physical noise source and performs health tests to check the quality of these raw noise bits. More information about health tests can be found in section 4 of [NIST SP 800-90B](https://doi.org/10.6028/NIST.SP.800-90B).

The driver for the `entropy_src` peripheral enables the Repetition Count and Adaptive Proportion tests, as specified in 4.4.1 and 4.4.2 of the same document.

These two tests have threshold values that determine what fails the tests. The thresholds must be appropriately set to minimize false-positives while still being able to detect failures in the physical noise source.

### Example: threshold for Repetition Count test
The Repetition Count test has a 16-bit threshold value that determines how many times a bit has to repeat consecutively before the peripheral considers the test has failed. 

NIST provides this formula to calculate the threshold: `1 + ceil(-log_2(α) / H)`, where `α` is the false-positive probability, and `H` is the min-entropy estimate of the physical noise source.

If the physical entropy source had ideal entropy (`H = 1`; a 0-bit and a 1-bit are equally likely), and we wanted a false-positive probability of `2^-40`, then the Repetition Count threshold would be `41`.

The min-entropy estimate is specific to the physical properties of the raw noise source, i.e., **there is no single value that applies to all noise sources**. Therefore, each integrator must calculate the test thresholds for their particular noise source and make that information available to the Caliptra firmware.

## Request
Fuse-style SoC registers to hold three 16-bit threshold values:

1. [the Repetition Count threshold](https://github.com/chipsalliance/caliptra-rtl/blob/8bb19ac0b1decac7da43fc69aa64eb2a8f22ab7c/src/entropy_src/data/entropy_src.rdl#L212C19-L212C19);
2. [the Adaptive Proportion low threshold](https://github.com/chipsalliance/caliptra-rtl/blob/8bb19ac0b1decac7da43fc69aa64eb2a8f22ab7c/src/entropy_src/data/entropy_src.rdl#L278); and
3. [the Adaptive Proportion high threshold](https://github.com/chipsalliance/caliptra-rtl/blob/8bb19ac0b1decac7da43fc69aa64eb2a8f22ab7c/src/entropy_src/data/entropy_src.rdl#L256).

The SoC would write to these registers on startup, which the `entropy_src` driver code will read to set the thresholds.

**Comment by Nitsirks** [comment]
Kor, can you provide the following info for the new register?

Name: 
Desc: 
Width: 
Reset Value: 
SoC Access Permissions: 
uC Access Permissions: 
Resetsignal:

**Comment by Nitsirks** [comment]
New registers are now available.

reg {
    name = "Caliptra iTRNG Entropy Configuration 0";
    desc = "Adaptive threshold values for entropy source health tests.";
    field {sw=rw; resetsignal=cptra_rst_b;} low_threshold[16]=0;
    field {sw=rw; resetsignal=cptra_rst_b;} high_threshold[16]=0;
 } CPTRA_iTRNG_ENTROPY_CONFIG_0;

reg {
    name = "Caliptra iTRNG Entropy Configuration 1";
    desc = "Repetition count value for entropy source health tests.";
    field {sw=rw; resetsignal=cptra_rst_b;} repetition_count[16]=0;
    field {sw=rw; resetsignal=cptra_rst_b;} RSVD[16]=0;
 } CPTRA_iTRNG_ENTROPY_CONFIG_1;
