### ISSUE TITLE
Slave numbers and adress mismatch in rtl and document

### ISSUE THREAD

**Issue by tulugunavyasri** [chipsalliance/caliptra-rtl#198]
Hi,

Slave numbers and address range mismatch is being observed in rtl and simulation results, can you please share the updated hardware specification document for this.

Thanks,
Navya.

**Comment by Nitsirks** [comment]
@tulugunavyasri Could you provide more information about the mismatch you are seeing? Is this a documentation issue, or are you seeing a functional problem?

**Comment by tulugunavyasri** [comment]
Hi ,

The offset address which we are seeing in the register document provided by the caliptra and the address which are there in the register file in rtl are not matching.

[cid:1716eb89-38f8-47b5-8d0c-76817afe0533]

[cid:dfead24d-d70c-42bf-8f73-a4ff8c370fda]

Thanks,
Navya
________________________________

**Comment by Nitsirks** [comment]
@tulugunavyasri
Which register document are you referring to?

**Comment by tulugunavyasri** [comment]
Hi,

Please find the link for register document
clp — clp Reference (chipsalliance.github.io)<https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp>

Thanks,
Navya
________________________________

**Comment by Nitsirks** [comment]
@tulugunavyasri 
I just did a sanity check with RTL and I don't see any mismatches on the address ranges here. Is there a specific component that you are seeing a mismatch for?

**Comment by Nitsirks** [comment]
@tulugunavyasri
Please provide which components you believe to be mismatching with the reg documentation so that we can resolve the issue. Otherwise, we will close this issue.

**Comment by tulugunavyasri** [comment]
Hi ,

Sorry for the miscommunication, actually slave address numbers and address range is not matching with the hardware specification, can you please provide if there is any updated document.

[cid:95699490-2ab6-44f7-9170-c929e3a9f225]


[cid:4a0997d7-7d7c-4317-b704-6bb79ce510a5]

Thanks,
Navya
________________________________

**Comment by Nitsirks** [comment]
@tulugunavyasri 
The documentation you linked is the correct documentation, it's generated from the RDL and it matches the RTL implementation. If there is a mismatch somewhere, please be specific and detail which component is mismatching.

**Comment by Nitsirks** [comment]
@tulugunavyasri
Closing this issue. If you find there is a real mismatch, please document exactly what is mismatching and file another issue so that we can properly investigate.
