### ISSUE TITLE
Reserve GENERIC_INPUT_WIRE[0] for zeroization status

### ISSUE THREAD

**Issue by varuns-nvidia** [chipsalliance/caliptra-rtl#199]
FIPS requires a dedicated zeroization status signal. Spec changes tagged for https://github.com/chipsalliance/Caliptra/issues/52

Not expecting any RTL changes here, but documentation changes.

**Comment by bharatpillilli** [comment]
@calebofearth let's add this to integration and design specs

**Comment by calebofearth** [comment]
This is completed via https://github.com/chipsalliance/caliptra-rtl/pull/207
