### ISSUE TITLE
Update documentation for force locking the SHA Accelerator.

### ISSUE THREAD

**Issue by mhatrevi** [chipsalliance/caliptra-rtl#216]
Currently ROM writes a 0 to sha512_acc_csr.LOCK to forcibly lock the SHA accelerator on a fatal error. This force lock behavior needs to be documented in the register doc. NCC flagged the ROM code that did this, stating it was incorrect based on the register documentation.

**Comment by Nitsirks** [comment]
Writing 0 to the LOCK register may incidentally acquire the lock for Caliptra if it's currently unlocked, but in that case shouldn't you just follow the API and read LOCK?

There is no capability to forcibly take the lock from the SoC. If that feature is required, it's a separate issue. If writing 0 works to forcibly take the lock away, that's a bug and we need to fix it. It doesn't appear to me that writing 0 would work if the SoC has the LOCK, but I can try it out and see if it's somehow taking the lock.

**Comment by upadhyayulakiran** [comment]
I ran a quick test to write/read 0s and 1s. Writing a 0 doesn't seem to change the register value if it's already unlocked. Writing 0 when it is locked also does not take the lock away. 

![image](https://github.com/chipsalliance/caliptra-rtl/assets/125604693/abab3a2b-8d13-4d92-a663-fa3887a1a7e8)

**Comment by bharatpillilli** [comment]
Also if the SoC is using peripheral, then although that crypto is within Caliptra boundary that is still a SOC resource. Why do we need to lock that resource if it's not faulty?

**Comment by bharatpillilli** [comment]
I understand that some vague rule states that but can we not explain and understand why we need to lock a resource that is not faulty?

**Comment by mhatrevi** [comment]
> I understand that some vague rule states that but can we not explain and understand why we need to lock a resource that is not faulty?

It's for satisfying this https://github.com/chipsalliance/caliptra-sw/issues/394 FIPS requirement.

**Comment by bharatpillilli** [comment]
I reopened that issue to discuss there. We don't want to reopen HW and additional functions now. We need to push this to be handled by soc integration logic or elsewhere. This is a good exercise for us to go through for any late issues that we encounter

**Comment by mhatrevi** [comment]
Based on my discussion @upadhyayulakiran, this can be done with the existing functionality. FW needs to write a 1 to release the lock and read a 0 back to ensure the SHA Acc is locked.

**Comment by bharatpillilli** [comment]
Unless I misunderstood, her waveform above doesnt seem to do so...right @upadhyayulakiran ?

**Comment by Nitsirks** [comment]
Caliptra won't have write permission to the LOCK register if it's not the one who acquired the LOCK. Writes to LOCK are only enabled by the valid user (Correct PAUSER from SoC, or Caliptra - whichever acquired the lock)

**Comment by upadhyayulakiran** [comment]
Provided it's a valid user, only way to unlock is to do a write 1 to clear, and then read the lock reg (which reads back a 0) and that will set it. Once SOC has the lock, writing a 0 will not force unlock it.

**Comment by bharatpillilli** [comment]
Closing the issue as RTL doesn't behave as assumed
