### ISSUE TITLE
Unable to generate program.hex file

### ISSUE THREAD

**Issue by saikumar0508** [chipsalliance/caliptra-rtl#222]
Hi,

Unable to generate program.hex file for following test_suites at integration level .

caliptra_demo
caliptra_fmc
caliptra_rt
smoke_test_uart
smoke_test_qspi
smoke_test_datavault_basic
smoke_test_datavault_lock
smoke_test_datavault_mini
smoke_test_datavault_reset

Path : /nsfs/devarsim2/smegavat/RoTSS/caliptra-rtl-caliptra-sw/src/integration/test_suites/

Command used : make -f $CALIPTRA_ROOT/tools/scripts/Makefile TESTNAME=caliptra_demo program.hex

error message :

/nsfs/devarsim2/smegavat/RoTSS/caliptra-rtl-caliptra-sw//src/integration/test_suites/caliptra_demo/caliptra_demo.c:36:22: warning: extra tokens at end of #ifdef directive
   36 | #ifdef CPT_VERBOSITY   
      |                      ^
/nsfs/devarsim2/smegavat/RoTSS/caliptra-rtl-caliptra-sw//src/integration/test_suites/caliptra_demo/caliptra_demo.c:38:7: warning: extra tokens at end of #else directive [-Wendif-labels]
   38 | #else   
      |       ^
/nsfs/devarsim2/smegavat/RoTSS/caliptra-rtl-caliptra-sw//src/integration/test_suites/caliptra_demo/caliptra_demo.c: In function 'idevid':
/nsfs/devarsim2/smegavat/RoTSS/caliptra-rtl-caliptra-sw//src/integration/test_suites/caliptra_demo/caliptra_demo.c:131:27: error: 'CLP_KV_REG_PCR_ENTRY_0_0' undeclared (first use in this function); did you mean 'CLP_PV_REG_PCR_ENTRY_0_0'?
  131 |     reg_ptr = (uint32_t*) CLP_KV_REG_PCR_ENTRY_0_0;
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~

Please review and let me know if I'm missing anything

Thanks,
Saikumar

**Comment by Nitsirks** [comment]
Please see the L0_regression.yml file for an up to date list of directed tests that we currently maintain. Tests not in this list may be deprecated.

**Comment by calebofearth** [comment]
FYI, for reference re: caliptra_demo, caliptra_fmc, caliptra_rt
https://github.com/chipsalliance/caliptra-rtl/issues/156
