### ISSUE TITLE
[ECC] Report failure in signing if generated signature has s=0

### ISSUE THREAD

**Issue by mojtaba-bisheh** [chipsalliance/caliptra-rtl#223]
Based on NIST FIPS 185-5 page 24, section 6.4.1, in ECC signing operation, if r = 0 or if s = 0, then output failure. 
https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf
Although the situation for r=0 has been highlighted in RFC6979, there is no statement for s=0 in that document. However, this failure (s=0) should also be added into design.

**Comment by bharatpillilli** [comment]
Hi Mojtaba - same questions as last one...why found now? how come other tests or FPV didnt catch?

**Comment by mojtaba-bisheh** [comment]
Hi Bharat, this issue came out from our today FPV meeting. The review of
ECC FPV is not completed yet and that’s the reason they didn’t catch it
before.

**Comment by mojtaba-bisheh** [comment]
The bug has been fixed internally as follows:
`assign s_output_outofrange      = signing_process & (hw_s_we & (read_reg == 0));`

**Comment by mojtaba-bisheh** [comment]
https://github.com/chipsalliance/caliptra-rtl/pull/240 sync fixed this.
