### ISSUE TITLE
Unable to generate program.hex file

### ISSUE THREAD

**Issue by saikumar0508** [chipsalliance/caliptra-rtl#224]
I checked L0_regression.yml file and below 3 tests are there in the list

smoke_test_datavault_basic
smoke_test_datavault_lock
smoke_test_datavault_reset

While generating program.hex file for these tests I'm facing below error.

/nsfs/devarsim2/smegavat/RoTSS/caliptra-rtl-caliptra-sw//src/integration/test_suites/smoke_test_datavault_basic/smoke_test_datavault_basic.c:25:10: fatal error: datavault.h: No such file or directory
25 | #include "datavault.h"
| ^~~~~~~~~~~~~
compilation terminated.
make: *** [smoke_test_datavault_basic.o] Error 1

**Comment by Nitsirks** [comment]
The Makefile should be getting this out of libs directory like any other include. Not sure why this include is giving you issues.

**Comment by Nitsirks** [comment]
Duplicate
