### ISSUE TITLE
Regression setup

### ISSUE THREAD

**Issue by saikumar0508** [chipsalliance/caliptra-rtl#225]
Hi,

Can you please provide regression steps to run L0_regression.yml. 

Thanks,
Saikumar

**Comment by calebofearth** [comment]
Please refer to this section from the README which documents usage of the Python L0 regression script:
https://github.com/chipsalliance/caliptra-rtl#verilator-steps

**Comment by calebofearth** [comment]
@saikumar0508 is this documentation sufficient for your use case? If so, let's close this issue. Thanks.
