### ISSUE TITLE
Unloaded/Undriven ports/pins issue in synthesis

### ISSUE THREAD

**Issue by Syed-mudabbir-ahsan** [chipsalliance/caliptra-rtl#228]
Hi [bharatpillilli](https://github.com/bharatpillilli)

We are facing unloaded and undriven pins issue in RTL, I have added report as an attachment as the report is huge, Kindly check the report and help us to solve these issues as we are gated with these for our upcoming deliverables.
Adding a brief count of the issue:
Total number of unloaded sequential elements in design 'rotss_top' : 453
Total number of unloaded ports in design 'rotss_top' : 23
Total number of unloaded combinational elements in design 'rotss_top' : 1196
Total number of hierarchical undriven pins in design 'rotss_top' : 683
Total number of combinational undriven pins in design 'rotss_top' : 4
[unloaded_undriven_report.txt](https://github.com/chipsalliance/caliptra-rtl/files/12743782/unloaded_undriven_report.txt)

Regards,
Syed.

**Comment by bharatpillilli** [comment]
@Nitsirks - can you plz address this question

**Comment by Nitsirks** [comment]
Cleaning these up may be an exercise for Gen2 or a later release. As of now you'll need to waive or work around them unless there is a functional issue.

**Total number of unloaded sequential elements in design 'rotss_top' : 453**

- Majority of these are from design re-use. Your tools can safely optimize them away.
- Investigating the large number of flops in ECC, may be a gate count optimization here.

**Total number of unloaded ports in design 'rotss_top' : 23**

- itrng signals are unused if CALIPTRA_INTERNAL_TRNG is undefined. This should have been behind ifdef but interface is frozen.
- PPROT is unused, should have been removed.
- PADDR bits. You could set CALIPTRA_APB_DATA_WIDTH to `CALIPTRA_SLAVE_ADDR_WIDTH(`CALIPTRA_SLAVE_SEL_SOC_IFC)

**Total number of unloaded combinational elements in design 'rotss_top' : 1196**

- Your tools should optimize these away. We won't be reviewing unloaded combinatorial signals.

**Total number of hierarchical undriven pins in design 'rotss_top' : 683**

- Primarily parameters in VEER core. Fanout of 0 on everything except perr_dat_ff which is related to the icache that we don't instantiate. If this is an issue, it needs to be filed on VEER repository.
- This one doesn't make sense, we don't have a 17th array element for this signal only 16:0 hpin:rotss_top/u_caliptra/ahb_lite_bus_i/ahb_lite_resp_disable_i[17] 	 (fanout : 1)

**Total number of combinational undriven pins in design 'rotss_top' : 4**

- Not reviewing combinatorial pins

**Comment by Syed-mudabbir-ahsan** [comment]
Hi @Nitsirks , @bharatpillilli 

Thank you for quick response, as you have mentioned Cleaning these up may be an exercise for Gen2 or a later release. As of now you'll need to waive or work around them unless there is a functional issue. **Can you please let us know the Estimated time for the Gen2 or later release**

**Comment by Nitsirks** [comment]
There are no plans to make any additional changes for 1p0 except for approved bug fixes.

**Comment by Syed-mudabbir-ahsan** [comment]
Hi @Nitsirks @bharatpillilli 

What are the approved bug fixes, where can i refer these list of approved bug fixes, can you please help me to refer these bugs.

**Comment by Nitsirks** [comment]
Issues filed here that are deemed functional bugs and approved in the workgroup will be fixed.
