### ISSUE TITLE
Challenges to run Caliptra at lower frequency

### ISSUE THREAD

**Issue by ayanavachakraborty** [chipsalliance/caliptra-rtl#229]
What are the specific hardware/rom changes required to run Caliptra design at lower frquency? One that I can think of is setting the baud rate right for UART. Beside that do we need to do any other changes in configuration or RTL/compiler switches?

**Comment by bharatpillilli** [comment]
UART is not part of Caliptra POR design - it is there as an instrumentation code for FW to use during development.

Our POR is 100Mhz to 450MHz from higher process node (TSMC 40nm) to lower process node (eg. TSMC 5nm) for lower and upper bounds.
