### ISSUE TITLE
Baud rate setting

### ISSUE THREAD

**Issue by ayanavachakraborty** [chipsalliance/caliptra-rtl#230]
Need clarification on 2 things:

1. Without any changes by running as is we do see the program counter of ROM executing uart prints but I don't see any activity in UART tx port nor we see any activity inside the UART block of caliptra in the simulation environment. I do have the _CALIPTRA_INTERNAL_UART_ switch enabled. Is there anything else that we're missing?
2. To set the UART baud rate correctly for lower frequency we followed the following link 
https://github.com/chipsalliance/caliptra-rtl/blob/440a21d2ce0173139273cf7261a66f490bc630f6/src/uart/doc/_index.md#setting-the-baud-rate
is there anything else we need to take in consideration?

**Comment by bharatpillilli** [comment]
UART is NOT a POR part of Caliptra design - only exists for FW to print during pre-silicon development and I dont know if they are using it.

**Comment by ayanavachakraborty** [comment]
Got it thanks for clarifying that. Closing the isssue.
