### ISSUE TITLE
RTL/Compiler Switches for differest platforms 

### ISSUE THREAD

**Issue by ayanavachakraborty** [chipsalliance/caliptra-rtl#232]
Where can we find the details of what rtl/compiler switches should be enabled for Simulation, ASIC and FPGA? To ensure as a user that we are running caliptra simulation/synthesis correctly specific to the targeted platform is there any user guide?

**Comment by bharatpillilli** [comment]
FPGA compilation is done by @attzonko ; he can answer the question.

Not sure you mean by simulation/asic but the pre-si env information is present in the README. (@calebofearth as FYI)
