### ISSUE TITLE
DFT scan insertion in Caliptra IP RTL and timing constraints

### ISSUE THREAD

**Issue by syaxiado** [chipsalliance/caliptra-rtl#242]
Three issues:
1. The Caliptra Integration Specification mentions that the scan_mode pin different than the conventional scan mode pins and this scan_mode pin must be asserted before going into actual DFT scan mode. Can you please specify the minimum amount of clocks between the assertion of these two pins? And also, what is the min width that scan_mode must be kept asserted? 
2. Same document specifies some flops to be excluded from the scan chain. Can you please specify which signals are those in the RTL? 
3. Can you please provide timing constraints for the IP? We are especially interested in: false paths, multi-cycle paths

**Comment by Nitsirks** [comment]
1) scan mode must be asserted at least 1 clock before the scan chain is toggled. This allows time for flops that may contain secrets to get cleared internally. Scan mode should remain asserted the entire time you are in scan operation.
2) The integration spec lists these signals more accurately now:
internal_obf_key (found in soc_ifc_reg)
ptra_scan_mode_Latched_d and ptra_scan_mode_Latched_f at the top level
3) we have not identified any false paths or multi cycle paths.

**Comment by Nitsirks** [comment]
@syaxiado Does this answer your questions? Can we close the issue?
