### ISSUE TITLE
Mailbox Protocol Error during apb protocol wait state read access

### ISSUE THREAD

**Issue by ayanavachakraborty** [chipsalliance/caliptra-rtl#244]
While reading the mailbox lock register (0x30020000) the read value is 0x1 always if apb transaction is a wait state type. It works only if the apb protocol transaction type is no wait state.

**Comment by Nitsirks** [comment]
From the APB Spec:

**IDLE** This is the default state of the APB interface.
**SETUP** When a transfer is required, the interface moves into the SETUP state, where the appropriate select
signal, PSELx, is asserted. The interface only remains in the SETUP state for one clock cycle and
always moves to the ACCESS state on the next rising edge of the clock.

**Comment by ayanavachakraborty** [comment]
The issue was on the sender side for not setting the psel signal. Thanks for clarifying. Closing the issue.
