### ISSUE TITLE
Non Fatal Error during mailbox access

### ISSUE THREAD

**Issue by ayanavachakraborty** [chipsalliance/caliptra-rtl#245]
We are trying to load the fmc code to the mailbox from SoC. We are following the mailbox protocol from the section 6.4 of the following link https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/Caliptra_Integration_Specification.pdf.

On reading the mailbox lock register (0x30020000) we see the mailbox status register (0x3002001c) moving to 0x240 value which is expected. But as soon as we load the caliptra_fw_load cmd (0x46574c44) the mailbox status register (0x3002001c) moving to 0x3c0. Has anyone faced that issue before? Does anyone know why the mailbox error is going high?

**Comment by Nitsirks** [comment]
Deviating from the API can result in the FSM going to error state. In this case while in the ready for command state, trying to write a register other than CMD, or to read the dataout register.

Do you have waveforms available for the failure?

**Comment by ayanavachakraborty** [comment]
The issue was on the sender side related to the following issue: https://github.com/chipsalliance/caliptra-rtl/issues/244. The has been resolved so closing it.
