### ISSUE TITLE
Test suite bringup with respect to design memory implementation 

### ISSUE THREAD

**Issue by dayanajayaraman** [chipsalliance/caliptra-rtl#249]
1. Our design has been updated with ROM memory dimension as [63:0] mem [6144]  end address is 'h17FF whereas in caliptra, imem - [7:0] ram [6144] [7:0]  end address 'hBFFF because of the modification is the memory implementation preload of image is not successful as the dma address reads are out of range. - How can we handle this to enable the stand alone C based test suite.

2. while generating hex image using RISCV tool chain how the AT can be handled for the modifications with respect to our memory implementations.

**Comment by bharatpillilli** [comment]
Discussed in Caliptra WG..closing it
