### ISSUE TITLE
What are the Caliptra Frequency limitations?  

### ISSUE THREAD

**Issue by UriSha1** [chipsalliance/caliptra-rtl#257]
HI ,
Assuming using Internal TRNG.
Would like to know if there is known limitation for Caliptra clock maximum frequency?
Is there any known limitation for the minimum clock frequency?

Thanks

**Comment by Nitsirks** [comment]
We don't have exact frequency limitations, but we've documented in the integration spec the following.

Synthesis experiments have so far found the following:

Design converges at 400MHz 0.72V using a cutting edge TSMC process.
Design converges at 100MHz using TSMC 40nm process.

**Comment by UriSha1** [comment]
Many Thanks Nitsirks.
