### ISSUE TITLE
[performance] req_hold is inadvertently asserted during entire sha accelerator mailbox read

### ISSUE THREAD

**Issue by Nitsirks** [chipsalliance/caliptra-rtl#259]
While SHA accelerator is reading the mailbox SRAM, the request hold logic gets asserted by mistake the entire time.

This can cause the uC or SoC polling the mailbox status register to hold for up to 32 clocks.

**Comment by andreslagarcavilla** [comment]
is this fixed now?

**Comment by calebofearth** [comment]
Yes, this is resolved by c932181fddc4461aaaed4cf7242af210d5c28842
