### ISSUE TITLE
Caliptra entropy requirements

### ISSUE THREAD

**Issue by akash-singh-NV** [chipsalliance/caliptra-rtl#262]
Can we document entropy quality requirement for 2 RNG options ?

**ITRNG with external physical noise source**
- what is the entropy per bit requirement for the physical noise source ?

**Shared RNG**

> "SOC will write to TRNG registers with NIST compliant entropy"

- Does this need to be NRBG output or DRBG output ?
- What is the entropy requirement ?

**Comment by howardtr** [comment]
Hi  @akash-singh-NV 

For the ITRNG with external physical noise source, we need a source that can generate entropy at 50KHz.  This should be documented in the Physical True Random Noise Source Section in the Caliptra IP Spec (which is getting updated right now) 

![itrng noise source](https://github.com/chipsalliance/caliptra-rtl/assets/30353679/6c1d37ef-8d72-487e-88cd-d3e451180c2f)

I'll have to hand it over to @Nitsirks for the Shared RNG requirement

**Comment by akash-singh-NV** [comment]
What is the expectation of entropy on the noise bits supplied at 50 KHz. Is there a minimum entropy per bit requirement or iTRNG can be programmed to work with any entropy by compressing more bits?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by howardtr** [comment]
Hi @akash-singh-NV - this block is leveraged from OT [here](https://opentitan.org/book/hw/ip/entropy_src/#description)

Hopefully this helps answer your question

In the terms of AIS31 classes, this block is meant to satisfy the requirements for a PTG.2 class physical entropy source, with “internal” entropy (an AIS31 term, meaning the min-entropy as measured just before the output pins) exceeding **0.997 entropy-bits/output-bit.** In NIST terms, this block satisfies the requirements for a “full-entropy” source, which requires even smaller deviations from ideal entropy, at the level of less than one part in 264.

**Comment by akash-singh-NV** [comment]
> In order to compensate for the fact our tests (like all realistic statistical tests) have finite resolution for detecting defects, we conservatively use 2048 bits of PTRNG noise source to construct each 384 bit conditioned entropy sample

Is there an option to compress more than 2048 bits into 384 bit in case input entropy comes out to be lower than 0.375 ?

**Comment by howardtr** [comment]
> > In order to compensate for the fact our tests (like all realistic statistical tests) have finite resolution for detecting defects, we conservatively use 2048 bits of PTRNG noise source to construct each 384 bit conditioned entropy sample
> 
> Is there an option to compress more than 2048 bits into 384 bit in case input entropy comes out to be lower than 0.375 ?

@akash-singh-NV - sorry for the delay.   I believe that this can be configured via [health_test_windows.fips_window](https://opentitan.org/book/hw/ip/entropy_src/doc/registers.html#health_test_windows--fips_window)

**Comment by andreslagarcavilla** [comment]
Is this issue resolved, can it be closed?

**Comment by akash-singh-NV** [comment]
> > > In order to compensate for the fact our tests (like all realistic statistical tests) have finite resolution for detecting defects, we conservatively use 2048 bits of PTRNG noise source to construct each 384 bit conditioned entropy sample
> > 
> > 
> > Is there an option to compress more than 2048 bits into 384 bit in case input entropy comes out to be lower than 0.375 ?
> 
> @akash-singh-NV - sorry for the delay. I believe that this can be configured via [health_test_windows.fips_window](https://opentitan.org/book/hw/ip/entropy_src/doc/registers.html#health_test_windows--fips_window)

@howardtr that'd work. Do you want to update this in the main spec as well ?

**Comment by andreslagarcavilla** [comment]
https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md says "TRNG is the digital logic and algorithms that are required for random number generation. It requires a physical entropy source input. See the Caliptra IP specification and [integration specification](https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md) for more information."

There is little other information on the TRNG in the main spec, which I think is appropriate. I think we only need to change the hw integration spec here.

**Comment by andreslagarcavilla** [comment]
The [Integration Parameters](https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md#integration-parameters) section of the iw integ spec has a table row on `iTRNG_DATA`. I will send a PR to link the more detailed OT info there to resolve this issue

**Comment by andreslagarcavilla** [comment]
Actually the [hw spec](https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraHardwareSpecification.md#integrated-trng) has a section here, with the details, so it's a matter of linking.

**Comment by andreslagarcavilla** [comment]
@akash-singh-NV @steven-bellock you might also want to review https://github.com/chipsalliance/caliptra-rtl/pull/364
