### ISSUE TITLE
Address phase and data phase are not as per AHB protocol

### ISSUE THREAD

**Issue by Syed-mudabbir-ahsan** [chipsalliance/caliptra-rtl#264]
Hi @bharatpillilli,

We are running tests on AHB path to access responder slaves through initiator0, we have observed that initiator0_address_ph is independent of clock since it is driven in always_comb block. due to this we are not seeing the behaviour as per the AHB protocol. There is only a minimum duration gap between address phase and data phase which is irrespective of clock cycles as you can see in below waveform, due to this don't you think the address phase and data phase of the same transfer may overlap at some point of time.

![MicrosoftTeams-image](https://github.com/chipsalliance/caliptra-rtl/assets/143068047/8f5d5972-1348-40af-a58d-8352254cf67a)

As per AHB protocol address phase and data phase should be on the different clock cycles
![image](https://github.com/chipsalliance/caliptra-rtl/assets/143068047/611a1dcc-b8f0-4cbf-80eb-d53326154895)

Can you please let us know if this is expected or kindly help us to understand this issue.

**Comment by Nitsirks** [comment]
Ahb does support a new address phase during a data phase. The mux block you are referencing here only sequences the phases from two initiators and presents them downstream as though they came from one.
