### ISSUE TITLE
Most (all?) integration parameters are not in the RTL

### ISSUE THREAD

**Issue by steven-bellock** [chipsalliance/caliptra-rtl#278]
Table 2 says
<html>
<body>

Parameter name | Width | Description
-- | -- | --
APB_ADDR_WIDTH | 32 | Width of the APB Address field. Default to 32.
APB_DATA_WIDTH | 32 | Width of the APB Data field. Default to 32.
APB_USER_REQ_WIDTH | TODO | Width of the APB PAUSER field.
CPTRA_SET_MBOX_PAUSER_INTEG | 5 | Each bit hardcodes the valid PAUSER for mailbox at integration time.
CPTRA_MBOX_VALID_PAUSER | [4:0][31:0] | Each parameter corresponds to a hardcoded valid PAUSER value for mailbox, set at integration time. Must set corresponding bit in the CPTRA_SET_MBOX_PAUSER_INTEG parameter for this valid pauser override to be used.
CPTRA_DEF_MBOX_VALID_PAUSER | 32 | Sets the default valid PAUSER for mailbox accesses. This PAUSER is valid when any VALID_PAUSER is unlocked or not set by INTEG parameter.
CPTRA_SET_FUSE_PAUSER_INTEG | 1 | Sets the valid PAUSER for fuse accesses at integration time.
CPTRA_FUSE_VALID_PAUSER | 32 | Overrides the programmable valid PAUSER for fuse accesses when CPTRA_SET_FUSE_PAUSER_INTEG is set to 1.

</body>
</html>

but, for example, `APB_ADDR_WIDTH` does not exist in the RTL.

**Comment by Nitsirks** [comment]
Unfortunately these are spread around the design and not conveniently located for integrators. We will consolidate these into one place at the top wrapper level for a future release.

I will update the integration spec to fix the names and add where they exist.
