### ISSUE TITLE
JTAG Debug support and documentation

### ISSUE THREAD

**Issue by lemonzinga** [chipsalliance/caliptra-rtl#280]
Looking for a clear JTAG documentation. 
The current [doc](https://github.com/chipsalliance/caliptra-sw/blob/850d604ef0b7485d6fdc803d64003e3a1b1222e4/hw-latest/fpga/FPGA_Instructions.md#jtag-debug-doc-wip) is not clear and is missing more information on the following : 

- Provide any JTAG commands specific to Caliptra
- How to enable **SW breakpoint based debugging**
- How to get GDB operational
- Steps to configure JTAG for non-openOCD debuggers

**Comment by FerralCoder** [comment]
@jlmahowa-amd, please add some details to the doc based on your JTAG testing

**Comment by jlmahowa-amd** [comment]
I created a PR to update the FPGA JTAG documentation:  https://github.com/chipsalliance/caliptra-sw/pull/1159
That _partially_ addresses the asks.
- Provide any JTAG commands specific to Caliptra - Provides details of how to access Caliptra's registers using OpenOCD.
- How to enable SW breakpoint based debugging - Normal GDB commands.
- How to get GDB operational - Added more details of how to launch GDB.
- Steps to configure JTAG for non-openOCD debuggers - Provided pin map for JTAG signals on PMOD connector.

Honestly the current setup is not very repeatable. I have a plan to connect the JTAG signals to Zynq GPIO signals and use existing OpenOCD drivers to simplify the flow. That would eliminate the need for an external debugger and allow GDB to be launched from the Zynq platform.

**Comment by FerralCoder** [comment]
Addressed by https://github.com/chipsalliance/caliptra-sw/pull/1159.
