### ISSUE TITLE
Caliptra integrator requirements out-of-date

### ISSUE THREAD

**Issue by varuns-nvidia** [chipsalliance/caliptra-rtl#291]
https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md#soc-integration-requirements
Has outdated items like CSR signing key.
Scrub against main spec to ensure all requirements are captured (IDevID certificate requirements is one example gap)

**Comment by bharatpillilli** [comment]
There is an ongoing PR to add couple of rows for to that table and we will also remove the CSR signing key rows...what else HW integ requirements exist for IDevID?

**Comment by varuns-nvidia** [comment]
The high-level problem is that the main spec doesn't explicitly call out requirements to integrators. Scrubbing through it, here's what I think we need to add here:

1. Explicitly note what fuses need to be backed by physical fuses. For example, owner_pk_hash can come from flash instead, but field entropy threat model assumes fuse.
2. Must program the IDevID certificate with fields defined per https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#idevid-certificate
3. Must use internal TRNG for production
4. Add https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#fuse-requirements
5. Clarify the powergood reset intention with regard to firmware recovery flows

**Comment by varuns-nvidia** [comment]
> @varuns-nvidia - I think number#3 point above is a change in POR from what we have been stating. Not everyone has been conveying to us exactly how they intend to implement TRNG. I would rather say "suggest" than "must".

Fair, can interpret the change here as non-mandatory https://github.com/chipsalliance/Caliptra/commit/52c7100186f64784052df9e6626d9363be3fc200

**Comment by andreslagarcavilla** [comment]
Is this bug resolved now?
