### ISSUE TITLE
double-bit ECC failures that occur during load from ICCM do not set cptra_hw_error_fatal::iccm_ecc_unc

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-rtl#295]
To reproduce:

Corrupt a word in ICCM, and try to load it with the `lw` instruction.

The only symptoms that occur when this happens are an NMI with generic MCAUSE 0xf000_0001 (NMI_CAUSE_DBUS_NON_BLOCKING_LOAD_ERROR):

```
mcause: 0xf0000001,
mscause: 0x0,
mstatus: 0x1800,
mtval: 0x0,
cptra_hw_error_fatal: 0x0
cptra_hw_error_enc: 0x0
cptra_hw_error_non_fatal: 0x0
error_internal_intr_r: 0x0
```

If this happens in the field, it will difficult to root-cause it, as there doesn't seem to be any indication to the uC an ECC error occurred.

![Screenshot from 2023-11-13 01-01-10](https://github.com/chipsalliance/caliptra-rtl/assets/993854/0bebfde9-6347-44f3-8e8b-96f9240a24e1)

**Comment by Nitsirks** [comment]
Digging into VeeR logic here. Looks like the iccm ecc double error fires only on IFU requests to ICCM. When LSU does a DMA to the ICCM it just flags it as a bus error (same with DMA to DCCM as far as I can tell).

Found this in the PRM:
![image](https://github.com/chipsalliance/caliptra-rtl/assets/108370498/e601f6cf-05fb-44cd-98be-90c6a930ae88)

**Comment by bharatpillilli** [comment]
That makes sense because the data retrieval is not an IFU operation. This would be similar to operation on the bus where there is a parity error (I understand that our bus doesnt support parity errors :-)).

**Comment by korran** [comment]
@bharatpillilli I'm fine with the fault being a generic fault, but we need some mechanism to tell that ECC was the cause of the fault. When this happens, I would like to see the hardware set the iccm_ecc_unc bit in cptra_hw_error_fatal.

**Comment by calebofearth** [comment]
This error could be communicated to the SoC by writing to the cptra_fw_error_fatal register, which will also trigger the cptra_error_fatal output pin. Firmware should probably be doing this for any NMI it encounters already.

I understand that an NMI may be unrecoverable and firmware might be unable to set the register - but this is the best option with current hardware.

**Comment by korran** [comment]
The firmware is already setting the cptra_fw_error_fatal register, but the outside world doesn't know the reason for the failure.
