### ISSUE TITLE
Caliptra TB VCS simulation reported error, for jtagdpi

### ISSUE THREAD

**Issue by DerekWangScaleflux** [chipsalliance/caliptra-rtl#297]
Hi,
      I'm running Caliptra TB with VCS.

      Seen the following error:
![image](https://github.com/chipsalliance/caliptra-rtl/assets/127370484/e399996f-d81a-4108-9398-2bd9db1fb92a)

       Could you help to calarify ? What is missing?

Best Regards
Derek Wang

**Comment by calebofearth** [comment]
Can you try to compile the jtagdpi library as described here https://github.com/chipsalliance/caliptra-rtl/issues/148#issuecomment-1636340219? 

If that doesn't work - @mkurc-ant may be able to provide more insight.

**Comment by rdiwan2023** [comment]
Hi @calebofearth,
I am having the jtag.h and jtag.c in the compile.yml, but it's not working at my end.
@mkurc-ant , please help on this?


![image](https://github.com/chipsalliance/caliptra-rtl/assets/149656540/a540471d-4903-4e86-9001-590c72b4f2cb)

Thanks
Rohith

**Comment by calebofearth** [comment]
Hi @rdiwan2023 are you compiling the DPI first, and then compiling the RTL? The compiled DPI should be available to the VCS command used to compile RTL source.
Your error appears to be either (a) the DPI failed to compile or (b) the DPI compiled successfully, but the VCS compilation tool doesn't know where to find it. Could you clarify which one of these you're encountering?

**Comment by mkurc-ant** [comment]
Hi. I'm looking at the issue. I'll keep you posted once I find something.

**Comment by mkurc-ant** [comment]
Hi. I updated the makefile so that all sources are now correctly passed to VCS. Please take a look: https://github.com/chipsalliance/caliptra-rtl/pull/306

**Comment by calebofearth** [comment]
@DerekWangScaleflux does this resolve your issue?
