### ISSUE TITLE
In Caliptra TB 'fw' related tests compilation is failing.

### ISSUE THREAD

**Issue by rdiwan2023** [chipsalliance/caliptra-rtl#303]
Hi,
In the Caliptra TB 'fw_test_ecc_flow' compilation is failing with the below error:
 
![image](https://github.com/chipsalliance/caliptra-rtl/assets/149656540/6f39ef63-95d7-404d-a4a7-558ab527270b)

can you please check?

Thanks
Rohith

**Comment by Nitsirks** [comment]
Are you referring to fw_test_ecc384? I'm not seeing fw_test_ecc_flow.
The fw_test_* tests are maintained by the caliptra-sw team, they are busy finishing ROM 1.0 release. We will get an updated version of these tests after that is completed.

Right now, the tests that are kept up to date for caliptra_top_tb can be found here: src/integration/stimulus/L0_regression.yml
