### ISSUE TITLE
1p0 release has redundant files with this compilation is failing with 'multiple defination of _start' in Caliptra TB. 

### ISSUE THREAD

**Issue by rdiwan2023** [chipsalliance/caliptra-rtl#304]
Hi,
In the 1p0 release when I run the smoke_test_sha_256/smoke_test_sha_512 compilation is failing with below error.
![image](https://github.com/chipsalliance/caliptra-rtl/assets/149656540/69136a08-2fd4-4d3a-9813-6c5122db5d35)

What we see is in the relase area /Caliptra/src/integration/test_suites we have smoke_test_sha512.c which has the code to check the functionality and also we have smoke_test_sha512.s this is redundant file which causing 'multiple defination of _start' and making the compilation fail.
Please fix this and give a release.

Thanks 
Rohith

**Comment by Nitsirks** [comment]
Where are you seeing smoke_test_sha_512.s?

**Comment by rdiwan2023** [comment]
At /Caliptra/src/integration/test_suites/smoke_test_sha512

**Comment by Nitsirks** [comment]
I do not see smoke_test_sha_512.s in the repository, can you double check which release you have cloned?

**Comment by Nitsirks** [comment]
@rdiwan2023 Can you please clone a clean repository and confirm that you are still seeing this file? I do not see it in the repository.

**Comment by Nitsirks** [comment]
@rdiwan2023 Are you still facing this issue, or can we close it now?
