### ISSUE TITLE
scan_mode connection query of Caliptra

### ISSUE THREAD

**Issue by DerekWangScaleflux** [chipsalliance/caliptra-rtl#305]
Hi,
       I have one query regarding to the connection for scan_mode input.

       Is it okay and secure to put Caliptra logic into scan chain with directly input scan_mode ?
       Or should use the following signal :  
![image](https://github.com/chipsalliance/caliptra-rtl/assets/127370484/e18c1ac1-8e6a-48e9-bfa4-b0b5ac9c2bbe)

Best Regards
Derek Wang

**Comment by calebofearth** [comment]
Hi Derek, I'm not sure I clearly understand what you're asking.
Do you want to know what list of existing signals should be omitted from the scan chain?
Or are you trying to add new logic to Caliptra that is driven by scan_mode directly (and then add that new logic to the scan chain)?
Or is this the question about something else entirely?
Thanks

**Comment by Nitsirks** [comment]
**From the integration spec:**
For defense in depth, it is strongly recommended that debofuscation key flops are not on the scan chain.
Remove the following signals from the scan chain:
cptra_scan_mode_Latched_d
cptra_scan_mode_Latched_f
field_storage.internal_obf_key

**For the input to caliptra scan_mode:**
Must be set before entering scan mode. This is a separate signal than the scan chain enable signal that goes into scan cells. This allows Caliptra to flush any assets or secrets present in key vault and flops if the transition is happening from a secure state.

Your clock gate cells need to connect to the real scan enable. Caliptra requires an earlier indication (at least 1 cycle) to flush secrets, that pin exists at the top level wrapper to caliptra.

**Comment by Nitsirks** [comment]
@DerekWangScaleflux does this answer your question?

**Comment by DerekWangScaleflux** [comment]
Yes, it got solved. Thanks a lot.
We could close this one.
