### ISSUE TITLE
Hardware and Software Error Encoding

### ISSUE THREAD

**Issue by Syed-mudabbir-ahsan** [chipsalliance/caliptra-rtl#312]
Hi @bharatpillilli 

Can we please help me to get more details on CPTRA_HW_ERROR_ENC and CPTRA_FW_ERROR_ENC registers, i can see in register sheet that they are encoded error values for hardware and software errors, Can you please let us know what is the use case of these registers.

Thanks.

**Comment by calebofearth** [comment]
CPTRA_HW_ERROR_ENC is currently a placeholder for future development - it's not used right now. Bit encodings for [CPTRA_HW_ERROR_FATAL](https://chipsalliance.github.io/caliptra-rtl/main/external-regs/?p=caliptra_top_reg.generic_and_fuse_reg.CPTRA_HW_ERROR_FATAL) indicate the cause of a FATAL error (likewise for [CPTRA_HW_ERROR_NON_FATAL](https://chipsalliance.github.io/caliptra-rtl/main/external-regs/?p=caliptra_top_reg.generic_and_fuse_reg.CPTRA_HW_ERROR_NON_FATAL))

The FW ERROR ENC registers would be defined by the software team - there is not currently any use-case for these registers either.
