### ISSUE TITLE
Block Level test failures in 0P1 release

### ISSUE THREAD

**Issue by tnsri** [chipsalliance/caliptra-rtl#316]
Hi ,

Ran block level testcases for HMAC,ECC,DOE,SHA256,andSHA512 and found few failures.  
Attached xls for failures. can you please comment on this.

[Block level Testcase status.xlsx](https://github.com/chipsalliance/caliptra-rtl/files/13486675/Block.level.Testcase.status.xlsx)

Thanks,
Navya

**Comment by mojtaba-bisheh** [comment]
The block level testcases for this project are based on the following testbenches:

ecc_top_tb: This testbench verifies the functionality of the ECC module.
hmac_ctrl_tb: This testbench verifies the functionality of the HMAC module.
sha512_ctrl_32bit_tb: This testbench verifies the functionality of the SHA-512 module.
sha256_ctrl_tb: This testbench verifies the functionality of the SHA-256 module.
doe_core_cbc_tb: This testbench verifies the functionality of the DOE core module.

The other testbenches in the project can be ignored, as they were used for development purposes only.

**Comment by tnsri** [comment]
Hi,

Thank you for the update but ecc_top_tb this is failing , we are passing ecc_test_vectors file as test vectors is this the correct one, because i see there is a mismatch between the expected output and the generated one i.e. got values.can you please confirm on this.

Thanks,
Navya

**Comment by mojtaba-bisheh** [comment]
The required KAT for ECC is located here: src/ecc/tb/test_vectors/ecc_drbg_mbedtls.hex

**Comment by tnsri** [comment]
ok got it thank you . closing this issue.
