### ISSUE TITLE
Understanding mailbox_flow_done, nmi_intr.

### ISSUE THREAD

**Issue by Syed-mudabbir-ahsan** [chipsalliance/caliptra-rtl#323]
Hi @bharatpillilli 

I have few queries as mentioned below for which i couldn't get the complete flow of understanding from documents :
1. What is the significance of mailbox_flow_done, if data_avail is set why separate flow_done is required for indication to SoC
2. If we mask the nmi_pin bit in CPTRA_HW_ERROR_FATAL register then will it also separates the internal WDT interrupt nmi_intr.
3. What is the failure in KV read flow and write flow, what would cause it.

I kindly request you to please help us to understand these.

Thanks.

**Comment by RJMJJJ** [comment]
Thanks for the reply. When it is mentioned mailbox flow_done what all is expected in this flow?

**Comment by RJMJJJ** [comment]
Is below understanding, correct? mailbox_flow_done asserted when SOC writes to CALIPTRA_FLOW_STATUS 31st bit indicating it is done with MB flow,

**Comment by Nitsirks** [comment]
SoC does not write CPTRA_FLOW_STATUS, that is only writable by Caliptra.

Caliptra would set the bit in flow status which would assert the wire on the output of caliptra. An SoC could optionally use that wire as an interrupt, or if it's waiting for a mailbox flow to complete it could poll the status from caliptra registers.

During runtime, an SoC could requests a service from caliptra through the mailbox. Flow done was put in place for indicating that caliptra was done with a flow that didn't require it to return some data through the mailbox. If the service requires caliptra to return some data, that will be done through the mailbox and be indicated through data avail wire.

**Comment by RJMJJJ** [comment]
When SOC is sender and Caliptra is receiver then SOC gains MB lock, writes to MB and then sets the EXECUTE bit. Does setting EXECUTE bit indicate Caliptra of content available from SOC? Is there interrupt associated with this?

Section 6.3 of Integration Spec mentions about MB populataed by SOC sends interrupt to uC. Does above explain this interrupt or there is some other flow to generate interrupt? Where this interrupt is mapped to - is it part of any of the notif interrupts?

**Comment by Nitsirks** [comment]
Yes Caliptra uC is sent a notif interrupt when SoC populates the mailbox.

**Comment by RJMJJJ** [comment]
Which interrupt from the notif is it soc_ic_notif_intr or any other?

**Comment by Nitsirks** [comment]
Yes, it will trigger soc_ifc_notif_intr.
