### ISSUE TITLE
arguments for single_socreg_test  

### ISSUE THREAD

**Issue by saikumar0508** [chipsalliance/caliptra-rtl#328]
Hi,

Passing below arguments for single_socreg_test  facing below error

**ERROR with testing one soc_register; must provide method & name for +scoreg_method_name,eg. APB.CPTRA_TIMER_CONFIG**

command/arguments: 
	./simv.soc_ifc_tb -gui +CLP_MAX_CYCLES=200000000 +SECURITY_STATE=RANDOM +SOC_IFC_TEST=single_socreg_test **+SOCREG_METHOD_NAME = APB.CPTRA_TIMER_CONFIG** -gui

**+SOCREG_METHOD_NAME = APB.CPTRA_TIMER_CONFIG** not sure how to pass this argument please guide me on this. Attaching snippet for referrence.

![Capture](https://github.com/chipsalliance/caliptra-rtl/assets/145448325/c5fab397-a243-454e-95a0-8292636751e4)

Thanks,
Sai

**Comment by calebofearth** [comment]
It looks like the issue might just be whitespace used in your command - instead of 
`+SOCREG_METHOD_NAME = APB.CPTRA_TIMER_CONFIG`
can you try
`+SOCREG_METHOD_NAME=APB.CPTRA_TIMER_CONFIG`

**Comment by saikumar0508** [comment]
Yes you are right. I tried by removing whitespace and it's working fine.

Thanks,
Sai
