### ISSUE TITLE
[Integration spec] Document full cold boot flow from integrator perspective

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-rtl#334]
I wasn't able to find documentation of the things an integrator is supposed to do to boot Caliptra. Steps like:

1. Assert CPTRA_POWER_GOOD
2. Populate fuse registers
3. Write fuse_write_done register
4. Write BOOTFSM_GO register

Is this something that would make sense to document in the [hardware integration spec](https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md).

**Comment by Nitsirks** [comment]
I think this figure in that doc is meant to detail that.

Figure 3: Reset rules and timing diagram

@bharatpillilli maybe we can be more explicit in the spec so the information is easier to find?

**Comment by jhand2** [comment]
Got it, that diagram is helpful. Ya I think it would be good to explicitly list what is expected from the SoC. In particular, I don't think it says the SoC needs to assert BOOTFSM_GO.

**Comment by bharatpillilli** [comment]
> I think this figure in that doc is meant to detail that.
> 
> Figure 3: Reset rules and timing diagram
> 
> @bharatpillilli maybe we can be more explicit in the spec so the information is easier to find?

Ack Mike!

**Comment by jhand2** [comment]
> BootFSM Go is only required when HW Break point is set -otherwise it should not be gating

Ah, I didn't know that. Thanks for the clarification.
