### ISSUE TITLE
Caliptra support for PRNG integrity and health check

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#337]
Does Caliptra have the testing logic required to check the integrity and health of the PRNG by running some bist logic with fail/pass or is that expected to be done externally?

**Comment by howardtr** [comment]
Hi,

yes - Caliptra has the [entropy_src](https://opentitan.org/book/hw/ip/entropy_src/index.html) module that runs the health checks as defined by SP800-90B (Repetition, Adaptive Proportion).  Additionally adds Bucket + Markov tests
