### ISSUE TITLE
READY_FOR_FW is not asserted by Caliptra microcontroller

### ISSUE THREAD

**Issue by dc-nt** [chipsalliance/caliptra-rtl#347]
I am conducting Caliptra RTL testing in our SOC simulation environment. It includes Caliptra RTL and rom code.  
I followed the Caliptra boot flow sequence, and polling for the READY_FOR_FW event, but it did not occur.
The following is the sequence that I did:
    1. Cptra_pwrgood is asserted to the Caliptra IP block.
    2.  Cptra_rst_b is de-asserted to the Caliptra IP block.
    3.  Set the Caliptra BootFSM_BrkPoint strap signal.
    4.  Set the security state in DebugLocked and Production modes.
    5. Caliptra IP asserts Ready_For_Fuse wire to the SoC.
    6. The SoC populates the fuse registers (fuse_uds_seed, fuse_field_enthropy, OBF_KEY).
    7. Set the CPTRA_FUSE_WR_DONE bit. 
    8. Caliptra IP de-asserts Ready_for_Fuse wire.
    9. SOC Polling READY_FOR_FW signal, but it did not assert !!!
Am I missing anything?

**Comment by Nitsirks** [comment]
Setting the BootFSM_BrkPoint will cause Caliptra to enter a wait state until BOOTFSM_GO is set.

Either do not set the break point strap, or you need to also write BOOTFSM_GO after fuse done.
