### ISSUE TITLE
Netlist synthesis data

### ISSUE THREAD

**Issue by UriSha1** [chipsalliance/caliptra-rtl#348]
HI ,

According https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md
The Netlist synthesis data table Total Area 337088.

1. Can you clarify if this number is related to mm^2 or actually in Gate Count(Nand2)?
2. Please specify for what Process the the numbers are related? to TSMC 5nm or 40nm ? 
   (both numbers mentioned if searching the word 'TSMC' - confusing information)

Thanks

**Comment by steven-bellock** [comment]
> The area is expressed in units of square microns.

So μm<sup>2</sup>.

**Comment by Nitsirks** [comment]
The reference to TSMC 5nm in the spec should be removed, that was referencing the initial DC experiments done with 5 nm process files. The partner that collected the actual synthesis data is not releasing which process node they are working with.

Quote from the Integration Spec:
"The target foundry technology node is an industry standard, moderately advanced technology node as of 2023 September."
