### ISSUE TITLE
Type of data on itrng_data

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#350]
The random number value on PTRNG interface itrng_data is expected to be raw random data or post processed i.e. conditioned one. Will Caliptra accept the non post processed raw random data?

**Comment by akash-singh-NV** [comment]
What's the reason to expect processed noise data on ITRNG interface ? Isn't entropy_src module of ITRNG expected to implement conditioning and health tests ?
