### ISSUE TITLE
Synthesis frequency targeting 500Mhz

### ISSUE THREAD

**Issue by DerekWangScaleflux** [chipsalliance/caliptra-rtl#351]
Hi,
      For Caliptra synthesis targeting 500Mhz, we are seeing timing violation, mainly from memory --> CPU logic --> to memory.
      Is is possible to add registers on the ICCM/DCCM interface to improve timing ?

Best Regards
Derek Wang

**Comment by calebofearth** [comment]
This is not currently an option. Please file this as a feature request to the VeeR EL2 repository.
