### ISSUE TITLE
Caliptra resets

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#352]
1] Is cptra_rst_b warm reset for Caliptra? What all it resets on assertion?
2] Is cptra_pwrgood cold reset for CAliptra? That resets all the blocks - RISC-V, AHB interconnect, Crypto block (including KV and the crypto engines), Data Vault, PCR, SOC interface block?
3] With WDT reset what all blocks in CAliptra are reset?

**Comment by Nitsirks** [comment]
Please check the integration spec, if we need to add clarity to the spec reopen the issue and let us know here.

cptra_rst_b is the warm reset. It resets everything not deemed "sticky".
cptra_pwrgood is the cold reset. It resets everything.
WDT is an internal function.
