### ISSUE TITLE
Doe scan test is having SVA errors.

### ISSUE THREAD

**Issue by rdiwan2023** [chipsalliance/caliptra-rtl#354]
Hi,
For caliptra provided TB, Doe scan test is passing with SVA errors in the simulation log. 
Can anyone please check?

![image](https://github.com/chipsalliance/caliptra-rtl/assets/149656540/29f37545-a819-424c-a20f-4b48bfb66e7a)

Thanks
Rohith

**Comment by upadhyayulakiran** [comment]
Hi Rohith,

If you look in the output folder, you should find two files:
doe_test_vector.txt
doe_test_vectors_all.txt

Can you send me those so I can debug further?

Thanks,
Kiran

**Comment by rdiwan2023** [comment]
Hi @upadhyayulakiran,
Yes I am not having the doe_test_vector.txt & doe_test_vectors_all.txt.
I am not able to find doe_test_gen.py file. where we will have this file?

Thanks
Rohith

**Comment by rdiwan2023** [comment]
@upadhyayulakiran,
I got the doe_test_gen.py file, I will invoke the script and give a run.

Thanks
Rohith

**Comment by upadhyayulakiran** [comment]
The output files look good. I've used the same vectors to manually override the doe inputs and the test is passing for me without SVA errors. Can you confirm these for me?

1. Are you using caliptra_top_tb as is to compile and run this test? Specifically, are you using caliptra_top_tb_services to inject the input vectors to the dut?
2. Are you manually overriding the obf key/IV/ciphertext anywhere for the FE flows of DOE block?

Also, can you check in the waves if you're seeing the right key/IV/ciphertext being driven on the inputs and check the core result?

**Comment by rdiwan2023** [comment]
@upadhyayulakiran,
Ok,I will check and let you know.

Thanks
Rohith
