### ISSUE TITLE
smoke_test_kv_securitystate is failing with Time out issue

### ISSUE THREAD

**Issue by rdiwan2023** [chipsalliance/caliptra-rtl#360]
Hi, 
In the caliptra provided TB, for smoke_test_kv_securitystate is failing with time out issue.

![image](https://github.com/chipsalliance/caliptra-rtl/assets/149656540/f27040ee-f820-4282-a590-7589368396b8)
![image](https://github.com/chipsalliance/caliptra-rtl/assets/149656540/f69e6b53-da96-4b20-9baa-086158f4ca5c)

Can you please check at your end?

Thanks
Rohith

**Comment by calebofearth** [comment]
Rohith,

You may review the GitHub actions on this repository for an example of this test running to completion successfully: https://github.com/chipsalliance/caliptra-rtl/actions/runs/7228169055/job/19697136775

Please check your environment, make sure you are using the latest repository, and ensure you've followed the instructions in the README.
