### ISSUE TITLE
Zeroize

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#362]
Fo all the Crypto blocks (SHAs, HMAC, ECC) there is zeroize input in signal description table. There is ZEROIZE bit in CTRL register of each of these blocks. 
So, zeroization is triggered by asserting the zeroize input or by setting the ZEROIZE bit of CTRL register through memory map address? 
Whichever one is used then what is the significance of other - i.e. if ZEROIZE bit is set then what is the use of zeroize input to the block. And if zeroize input is asserted then what is the use of ZEROIZE bit.

OR is it like set the ZEROIZE bit in CTRL register (register bank - is outside the crypto blocks) which asserts zeroize input to the crypto block.

**Comment by Nitsirks** [comment]
Zeroize functionality is described in the hardware specification. ROM and FW can zeroize crypto blocks after use by setting the zeroize bit in the control registers for that crypto block. Events like debug port unlock, or scan mode enabling also trigger zeroize to clear out potential secrets.

**Comment by RJMJJJ** [comment]
Hi,
My question is not about when zeroization happens but its about CTRL register bit and zeroize input port on each crypto module.

**Comment by Nitsirks** [comment]
The zeroize port on each crypto module is driven by two things - a pulse from the zeroize control register that ROM/FW use to clear secrets from the crypto engines, and any context switch into debug or scan mode will automatically trigger the zeroize port.
