### ISSUE TITLE
Sequential transfers with more than single burst type.

### ISSUE THREAD

**Issue by tnsri** [chipsalliance/caliptra-rtl#367]
Hi,

can you please confirm if we have a senario which covers sequential transfers with more than single burst type.

Thanks,
Navya

**Comment by tnsri** [comment]
HTRANS à SEQUENTIAL
HBURST à more than single burst

**Comment by tnsri** [comment]
HTRANS->Sequential
HBURST->More than single burst

**Comment by Nitsirks** [comment]
No, our microcontroller only supports sequential single burst transactions.

**Comment by RJMJJJ** [comment]
Is this limitation because of the pending_hsel logic in AHB-L decoder?

**Comment by Nitsirks** [comment]
No, hburst is hardwired to 0b000 in the VeeR core.

**Comment by RJMJJJ** [comment]
Is there any other version of source code available or any guidelines that can be provided to make hburst supporting more than single burst?

Thanks

**Comment by Nitsirks** [comment]
No there is not.

Do you have a particular concern? The AHB bus is entirely internal to Caliptra, only ROM and FW are exposed to it.

**Comment by RJMJJJ** [comment]
We were exploring for adding any other peripheral supporting multi-beat burst mode for the RISC-V access on the AHB-L interconnect.

**Comment by Nitsirks** [comment]
Adding peripherals to Caliptra is not a valid use case of Caliptra IP.
