### ISSUE TITLE
HREADY_OUT going low

### ISSUE THREAD

**Issue by tnsri** [chipsalliance/caliptra-rtl#368]
Hi ,

Can you please confirm if there any scenarios where the hreadyout from the slaves on AHB interconnect goes low thus latching the pending_hsel in AHB decoder RTL and stretching the data phase.

Thanks,
Navya

**Comment by calebofearth** [comment]
This might occur if a SHA accelerator operation is in progress when Caliptra FW makes a direct mode request to the mailbox. The active SHA accelerator operation forces a stall in the arbiter that drops hready.
See also: https://github.com/chipsalliance/caliptra-rtl/issues/326
