### ISSUE TITLE
JTAG port accessing ICCM/DCCM

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#369]
Does the JTAG port on Caliptra IP has access to ICCM and DCCM?
This is mainly required for Debug purpose.

**Comment by tmichalak** [comment]
@RJMJJJ yes it does. There is even a [test in CI](https://github.com/chipsalliance/caliptra-rtl/blob/main/.github/workflows/interactive-debugging.yml#L242) that demonstrates in simulation how it can be done using gdb and OpenOCD. The test essentially executes the [following commands](https://github.com/chipsalliance/caliptra-rtl/blob/main/src/integration/test_suites/infinite_loop/mem_access.gdb) to access the ICCM and DCCM.

**Comment by RJMJJJ** [comment]
Thanks
