### ISSUE TITLE
Verilator Actions fail due to missing RV GCC tool package

### ISSUE THREAD

**Issue by calebofearth** [chipsalliance/caliptra-rtl#371]
This Verilator run (https://github.com/chipsalliance/caliptra-rtl/actions/runs/7284166844/job/20212806445?pr=357) fails because it lost access to the 12.1.0 RV gcc toolchain we've been using.

See: [remove old multilib toolchain · stnolting/riscv-gcc-prebuilt@f21324a (github.com)](https://github.com/stnolting/riscv-gcc-prebuilt/commit/f21324a84dcba8e8288ce58b41a1f4e96c61b2a2).

We need a more stable image to compile code for Verilator Actions.

**Comment by mkurc-ant** [comment]
Hi. Sure, I'll look into that.
