### ISSUE TITLE
To run Jtag test using vcs tool

### ISSUE THREAD

**Issue by harithadhulipalla** [chipsalliance/caliptra-rtl#373]
Hi,

Please share the steps to simulate Jtag big bang test using vcs tool.

**Comment by calebofearth** [comment]
This is currently only supported in the Verilator action running here on GitHub in conjunction with the openocd tool.
I recommend trying to follow along with the [workflow steps](https://github.com/chipsalliance/caliptra-rtl/blob/main/.github/workflows/interactive-debugging.yml) to set up a similar build system in your local environment.

The Makefile does include vcs compilation steps for the jtag dpi and tcp server that this test relies upon, but the makefile is not currently connecting a GDB session in any capacity.
