### ISSUE TITLE
Query on using ARM_UD_MODEL switch for compiled memories

### ISSUE THREAD

**Issue by dayanajayaraman** [chipsalliance/caliptra-rtl#376]
Hi, For sram memories and ROM we are using memories generated from ARM compiler , in this we are observing that when ARM UD MODEL switch is used observing in LSU bus htrans and hrdata is coming in the same clock cycle with out ARM UD MODEL switch we are observing that the memories are driven X.

Recommendation is to use ARM UD MODEL for the ARM memories but we are observing the htrans and hrdata is coming in same clock cycle which is not expected behavior as per AHB protocol.

**Comment by Nitsirks** [comment]
What does ARM UD MODEL switch do?

**Comment by Nitsirks** [comment]
@dayanajayaraman If you are still having issues, we can have a discussion offline. Otherwise we'll close this issue due to inactivity

**Comment by dayanajayaraman** [comment]
Yes we can close the ticket the issue is fixed by disabling a scan mux inserted for dft path, ARM UD MODEL switch from tech cell lib  is causing 1ps delay in clk mux and the hmac_clk with 1ps delay is considering as next clock cycle , thus placed hrdata with 1ps delay not in next clock cycle of hmac_clk.
