### ISSUE TITLE
Checks are failing on missing RISC-V toolchain

### ISSUE THREAD

**Issue by andreslagarcavilla** [chipsalliance/caliptra-rtl#378]
All the checks that want to download

https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv64imc-3.0.0/riscv64-unknown-elf.gcc-12.1.0.tar.gz

are missing. This tarball is 404. It seems we need to update our pointers

**Comment by calebofearth** [comment]
Duplicate of #371

**Comment by andreslagarcavilla** [comment]
close as dupe
