### ISSUE TITLE
F/W Errors

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#379]
As per documentation the Firmware Fatal and Non-Fatal errors as given below, but in RTL the FW_FATAL_ERROR and FW_NON_FATAL_ERROR signals are tied to 1'b0. Is there RTL available with these signals driven with proper logic or any guideline to pull relevant signals to drive FW_FATAL_ERROR and FW_NON_FATAL_ERROR.

F/W Fatal:
- KAT errors.
- FIPS Self Test errors.
- Mailbox commands received after FIPS Shutdown request completes.
- Hand-off errors detected upon transfer of control from ROM to FMC or FMC to Runtime.
- Mailbox protocol violations leading the mailbox to an inconsistent state if encountered by ROM during cold reset flow.
- Firmware image verification or authentication failures if encountered by ROM during Cold Reset flow.
- Non-aligned access to ICCM or DCCM
- AHB access hangs, triggered through WD timer expiry
- AHB access outside of the decoding range

F/W Non-Fatal:
- Firmware image verification or authentication failures if encountered by ROM during Update Reset flow.
- Mailbox protocol violations leading the mailbox to an inconsistent state (if encountered by ROM during Update Reset flow).
- Cryptography processing errors.

**Comment by calebofearth** [comment]
The FW_ERROR registers you mention are set by firmware, not by hardware. Code executing on the RISC-V core will perform a write with a non-zero value to the FW_ERROR_FATAL/NON_FATAL registers when it detects one of the events listed above. Hardware does not (and should not) have awareness into these events or the capability to drive the value of the error register.

**Comment by RJMJJJ** [comment]
FW_ERROR_FATAL/NON_FATAL registers are set by F/W can you point out which of the listed error codes in below link are Fatal and which are Non-Fatal?
https://github.com/chipsalliance/caliptra-sw/blob/main/error/src/lib.rs

And do the contents of FW_ERROR_FATAL/NON_FATAL registers assert caliptra_error_fatal and caliptra_error_non_fatal interrupts respectively?

**Comment by calebofearth** [comment]
Yes, CPTRA_FW_ERROR_FATAL register causes cptra_error_fatal interrupt to assert, and CPTRA_FW_ERROR_NON_FATAL register causes cptra_error_non_fatal interrupt to assert.

Be sure to note the rules for how register writes are related to assertion/deassertion of the error interrupt pins, as described for [non_fatal](https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.soc_ifc_reg.CPTRA_FW_ERROR_NON_FATAL) and [fatal](https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.soc_ifc_reg.CPTRA_FW_ERROR_FATAL) error regs.

Regarding that firmware file - please post this question to the caliptra-sw repository. The hardware team does not have specific expertise into how the specification-defined error codes are mapped to software const values.

**Comment by RJMJJJ** [comment]
Thanks, will post the error code related question to the caliptra-sw repository.
