### ISSUE TITLE
Add lms-accelleration-available bit to capability register 

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-rtl#391]
Maybe HW_CONFIG?

**Comment by pranjal3060** [comment]
can I work on this issue

**Comment by calebofearth** [comment]
@pranjal3060 Thanks for your interest. I have submitted an implementation of this for review at #486 - it's quite a low-effort change, more of a decision about when we want to consume it and how the bit impacts API and core stability than any amount of technical effort. 

@korran , can you take a look at the PR? Is this necessary for 1.1? This issue has been overlooked for long enough that I assume the FW team has an alternative solution.
