### ISSUE TITLE
Caliptra uC is reading one extra entry from Mailbox SRAM causing unexpected ECC errors

### ISSUE THREAD

**Issue by amullick007** [chipsalliance/caliptra-rtl#399]
Hi, We are bringing up Mailbox testcases and observed the following scenario where an unexpected ECC error is getting fired. Below is our sequence.

1. SOC acquires the MBOX lock by reading MBOX_LOCK register. It returns 0 indicating that the lock has been acquired by SOC.
2. SOC writes MBOX command register.
3. SOC writes MBOX_DLEN register to 8 indicating that it has 8 bytes of data to write.
4. SOC writes MBOX_DATAIN register twice. This causes two writes to SRAM mailbox at addresses 0x0 and 0x1.
5. SOC writes MBOX_EXECUTE to 1 in order for uC to process the mailbox command.
6. When the mailbox state machine is in MBOX_EXECUTE_UC state, we are observing that Caliptra is reading SRAM mailbox at addresses 0x0, 0x1 and 0x2. The first two are expected as DLEN is 8. However the data at address 0x2 are all X and hence ECC error signal (soc_ifc_top1.i_mbox.sram_double_ecc_error) is going X.

We want to understand why the mailbox state machine is reading one extra entry from SRAM (DLEN + 4 bytes instead of DLEN bytes). Since the Mailbox SRAM is not initialized on reset, reading from addresses where there have been no previous writes will cause unexpected ECC errors.

Do Caliptra ROM initializes Mailbox SRAM during bring up?

Mailbox Command from SOC
![image](https://github.com/chipsalliance/caliptra-rtl/assets/131188754/0e81da11-df93-41e0-a60c-872d2a749bdc)

ECC error while Mailbox state machine is reading from address 0x2
![image](https://github.com/chipsalliance/caliptra-rtl/assets/131188754/b3a0e590-1662-4780-8afc-e0275c8537b4)

**Comment by Nitsirks** [comment]
Avirup, thanks for bringing this to our attention.

When reading dataout register, we trigger a read to the next address to load dataout with so that it is available for the next read. If this speculative read goes beyond the valid data in the mailbox we drop it on the floor and don't populate dataout with it.

Unfortunately there seems to be a disconnect between RTL and ROM. RTL is initializing the ICCM, DCCM and Mailbox while ROM only initializes the ICCM and DCCM. We're investigating this disconnect now.

**Comment by korran** [comment]
I recently added mailbox-sram randomization to the verilator model, but forget to check how that is affecting the tests. There are intermittent failures like this:

```
024-01-24T03:19:56.6820888Z         FAIL [9008.018s] caliptra-rom::rom_integration_tests test_fmcalias_derivation::test_upload_single_measurement
<snip>
2024-01-24T03:19:56.8774795Z  12,738,502 UART: [fwproc] Waiting for Commands...
2024-01-24T03:19:56.8775740Z  12,741,752 UART: [fwproc] Received command 0x4d454153
2024-01-24T03:19:56.8776681Z  12,748,046 UART: ROM Fatal Error: 0x00080005
2024-01-24T03:19:56.8777428Z  12,751,469 >>> mbox cmd response: failed
```

**Comment by korran** [comment]
> Does this mean that once RISCV comes up, it will clear all the mailbox contents and will not repsond to the already request mailbox command?

If we have the ROM clear the mailbox SRAM, what you are doing won't be possible.

**Comment by amullick007** [comment]
Does RTL/ROM currently do any mailbox SRAM scrubbing currently?

**Comment by Nitsirks** [comment]
All of our RTL testbench environments initialize the Mailbox SRAM to zeroes.

It looks like ROM is going to submit a patch to also initialize the mailbox.
