### ISSUE TITLE
Observing Mismatch in mailboxbox dataout when we are sending the first DWORD other than 32'h00000000

### ISSUE THREAD

**Issue by tnsri** [chipsalliance/caliptra-rtl#404]
Hi ,

In smoke_test_mbox test observing testfailure with datamismatch when the input mailbox data in is changed to a non zero value for first DWORD. Please find the snippets attached.
![image](https://github.com/chipsalliance/caliptra-rtl/assets/152272534/88188c80-448b-4158-9325-cae4b15195e3)
![image](https://github.com/chipsalliance/caliptra-rtl/assets/152272534/6bc12476-cf76-4cf6-acfa-6230708d6663)

Thanks,
Navya

**Comment by tnsri** [comment]
Can you please confirm when the correct testcase will be available.

Thanks,
Navya

**Comment by Nitsirks** [comment]
I've pushed a branch that updates the read back from the mailbox to utilize firmwares direct access.

[user/dev/michnorris/mbox_smoke_test_upd](https://github.com/chipsalliance/caliptra-rtl/tree/user/dev/michnorris/mbox_smoke_test_upd)

**Comment by tnsri** [comment]
Hi,

Can you please explain as to why are we reading the mailbox dataout content starting from soc_ifc base address, i do not see the addressess defined in caliptra_reg_defines. 

Thanks,
Navya

**Comment by Nitsirks** [comment]
Caliptra uC has direct access into mailbox sram for debug. Smoke tests are very basic tests for gating PRs, thorough testing of mailbox protocols are done in our UVM environment. This was a quick workaround provided to fix the behavior of the test.

**Comment by tnsri** [comment]
Thank you
