### ISSUE TITLE
Caliptra is commanded to enter DebugLocked and manufacturing state

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#409]
Caliptra Main spec Table 11 for DebugLocked and manufacturing state mentions: 
Caliptra is commanded to enter this state during the secure HVM process. Can you explain what is meant by commanded here? Is there any specific command that Caliptra receives from HVM? If yes, what is the command and how does the Caliptra receives it?

https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md

**Comment by Nitsirks** [comment]
There is no command, appropriately setting the security state bits will modify the ROM flow appropriately
