### ISSUE TITLE
SCAN Flops

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#411]
The Caliptra Integration Spec mentions below:
•	SOC must ensure that there are no SCAN cells on the flops that latch this key “internal” to caliptra.
•	SoC backend flows should not insert CSR signing key flops into the scan chain.

Other than these are there any flops which are not supposed to be part of scan? Especially the Fuse Registers?

Thanks

**Comment by Nitsirks** [comment]
The integration spec specifically calls out the obfuscation key flops:
cptra_scan_mode_Latched_d
cptra_scan_mode_Latched_f
field_storage.internal_obf_key

What document are you seeing references to CSR signing key?

**Comment by RJMJJJ** [comment]
Integration Spec V0.8, page 33, Table 7
SoC backend flows should not insert CSR signing key flops into the scan chain. Required by IDevID threat model.

Is this no more applicable? Because Integration Spec 1.0 does not mention this.
https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md

**Comment by Nitsirks** [comment]
The 1.0 spec is the most accurate. I believe all references to CSR signing key were removed.
