### ISSUE TITLE
PCR opcode not matching with tb services

### ISSUE THREAD

**Issue by tnsri** [chipsalliance/caliptra-rtl#412]
Hi,

In smoke_test_pcr_signing , there is one programming happening through kv for injection of privkey but im not able to find how that programming is done, because i do not see that opcode either 88 or 7 in caliptra_top_tb_services.

 printf("Inject PRIVKEY into KV slot 7\n");
 uint8_t privkey_inject_cmd = 0x88 + 0x7;
 
And this , for the below opcode 0X90 from tb_services i see it is injection of privkey, display and functionality are different they are conflicting     
    printf("Inject MSG into SHA512 digest\n");
    printf("%c", 0x90);
    
can you please confirm on the above two things.
    
Thanks,
Navya

**Comment by mojtaba-bisheh** [comment]
The opcode 0x90 is used to inject all required inputs for PCR_signing operation. 
1. It injects a constant value as privkey into KV, and the slot number is determined by KV_ENTRY_FOR_SIGNING.
2.  It injects a constant value as msg into sha512 pcr_sign port.

The piece of code for 0x88+0x7 remained from our previous debugging process and can be removed.
