### ISSUE TITLE
Why lifecycle value maintained in 2 registers

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#417]
There is security state's strap input to Caliptra. The last 2bits of this are lifecycle bits. These go to CPTRA_SECURITY_STATE register's lower 2bits.  There is also LifeCycle 2bits Fuse defined for CAliptra. Which during Fuse write gets written to fuse_life_cycle register in CAliptra.

Why does Caliptra have both a Fuse loaded register and strap inputs loaded to another register for Caliptra’s life cycle? What’s the relationship?

**Comment by bharatpillilli** [comment]
As documented, lifecycle fuse bits are not used in Caliptra 1p0 mode of usage. Its a placeholder for future Caliptra profile
