### ISSUE TITLE
fuse_soc_stepping_id and OWNER KEY MANIFEST PK HASH MASK

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#420]
fuse_soc_stepping_id (16bits) is added to SOC_IFC registers list, link given below:
https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.soc_ifc_reg.fuse_soc_stepping_id

But is not part of the Fuse Map link given below:
[Caliptra/doc/Caliptra.md at main · chipsalliance/Caliptra (github.com)](https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#fuse-map)

Can you confirm the Fuse programming time for these, as defined for other Fuses in Fuse Map?

Also, earlier OWNER KEY MANIFEST PK HASH MASK (4bits) was part of Fuse Map but is no more, so we can consider this as removed and no need to provision Fuses for same.

**Comment by bharatpillilli** [comment]
@varuns-nvidia - can u plz help with this question or point to the spec?

**Comment by varuns-nvidia** [comment]
SoC stepping ID is the last entry in https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#fuse-map
It was added to the spec in https://github.com/chipsalliance/Caliptra/pull/179

OWNER KEY MANIFEST PK HASH MASK was removed in https://github.com/chipsalliance/Caliptra/pull/142
