### ISSUE TITLE
Potential race between flop

### ISSUE THREAD

**Issue by Syed-mudabbir-ahsan** [chipsalliance/caliptra-rtl#436]
Hi Team

**We are facing an Spyglass Lint issue which reports potential race conditions between flip-flop output and its 
clock pin,** 
As per the below faddrf1_ff instance the dout is looped back to din with certain conditions:
![image](https://github.com/chipsalliance/caliptra-rtl/assets/143068047/0920d75b-a70b-4688-9502-68f9d72da63f)
![image](https://github.com/chipsalliance/caliptra-rtl/assets/143068047/acef6072-983f-41b9-88f0-3b6c04d5b524)
And this din from feedback path is used to drive the enable pin of rvdffiee module as shown below:
![image](https://github.com/chipsalliance/caliptra-rtl/assets/143068047/aa622776-aeda-4e94-8952-a8bfe23d8391)
The same enable is used as enable of TEC_RV_ICG module as shown below:
![image](https://github.com/chipsalliance/caliptra-rtl/assets/143068047/76678092-3795-4766-bd18-cd5cd5ad5355)

Can you please help us to check if this can be waived, or it causes an issue in design.

Thanks.

**Comment by Nitsirks** [comment]
We haven't encountered this particular spyglass check. I've reached out to another integrator to see if they have seen it.

Does spyglass report a schematic of the issue that we can see to help debug this?

**Comment by nstewart-amd** [comment]
CK-Q of flop (posedge) and active edge of clock gater (low level latch) should be 180 degrees phase offset.  
Please review your implementation of TEC_RV_ICG module.

**Comment by Nitsirks** [comment]
Please check your TEC_RV_ICG module as Norman said. Re-open the issue if you can provide more details.
