### ISSUE TITLE
Interrpts to EL2 CPU tied to 0

### ISSUE THREAD

**Issue by DerekWangScaleflux** [chipsalliance/caliptra-rtl#439]
Hi, Caliptra team,
      In the latest release ( 1p0 ), the following interrupts are tied to 0:

      
![image](https://github.com/chipsalliance/caliptra-rtl/assets/127370484/2be88ff2-6b05-40f2-90cd-ae02c9ebf3cd)

      Will these interrupts be used ?

Best Regards
Derek Wang

**Comment by DerekWangScaleflux** [comment]
Hi @Nitsirks ,
     We are defining the macro "CALIPTRA_INTERNAL_UART".
     Is uart interrupt being used ?

Best Regards

**Comment by Nitsirks** [comment]
There are still no interrupts from uart.

Caliptra ROM and FW do not use uart at this time, no need to enable it
