### ISSUE TITLE
[RTL Feature Request] Add fuse bits for enabling LMS verification and key revocation

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-rtl#44]
See https://github.com/chipsalliance/caliptra-sw/issues/19 for discussion/details.

Request to add the following fuse bits:

|  Name     | Size      |  ACL      | Fuse Programming Time | Description
| ---           | ---        | ---         | ---                                     | ---
| LMS VERIFY                      | 1               | ROM             | In-Field Programmable                           | <p>0 - Verify Caliptra firmware images with ECDSA-only</p><p>1 - Verify Caliptra firmware images with both ECDSA and LMS</p>
| LMS REVOCATION           | 32             | ROM             | In-Field Programmable                          | Bits for revoking LMS public keys in the key manifest

Approval questionnaire:
* **Is the RTL change due to a Spec change?** Yes
* **Is the Spec change approved?** No (https://github.com/chipsalliance/Caliptra/pull/37)
* **Is the spec updated?** Partially (need a corresponding change in the ROM spec about LMS verification)
* **Is the change needed in Caliptra 0p8 or 1p0 milestone?** Yes (1p0)
* **Does it have silicon area impact?** No
* **Does it have timing impact?** No
* **If the change impacts ROM/FMC/RT, did the FW reps approve the change already?** Yes (Vishal Soni approved ROM change)
* **Why should the change be intercepted in Gen 1?** Required to support LMS verification. PQC mitigations could be required in the Gen 1 timeline.
* **Can the change be handled outside of Caliptra?** No
* **If there is a schedule impact to Caliptra 0p8 or 1p0 milestone, is it approved by voting leads?**
* **If change completed (implies schedule impact is zero):** N/A (not completed)

RTL Impact: RTL change, Val collateral update, Validation & PR all together is 1 days and no milestone impact

**Comment by bharatpillilli** [comment]
Change PRd -> https://github.com/chipsalliance/caliptra-rtl/pull/124#pullrequestreview-1491465833
