### ISSUE TITLE
Mimimum number of cycles between cptra_pwrgood and cptra_rst_b

### ISSUE THREAD

**Issue by DerekWangScaleflux** [chipsalliance/caliptra-rtl#442]
Hi Caliptra team,
        Is there minimum number of cycles required between cptra_pwrgood and cptra_rst_b ?
        In the Caliptra project specifiction: 
![image](https://github.com/chipsalliance/caliptra-rtl/assets/127370484/17486381-4112-486a-b557-01f348ca0863)

      But it seems no related information could be found in the integration spec ?

Best Regards
Derek Wang

**Comment by DerekWangScaleflux** [comment]
Hi @bharatpillilli ,
         Any updates ?

**Comment by Nitsirks** [comment]
PR in progress to update the spec to indicate 10 cycles between pwrgood and cptra_rst_b

**Comment by andreslagarcavilla** [comment]
PR merged in, addresses this issue

**Comment by andreslagarcavilla** [comment]
https://github.com/chipsalliance/caliptra-rtl/pull/449

**Comment by howardtr** [comment]
@Nitsirks - Thoughts on adding this as an assertion ?  (If it's not already there?)
