### ISSUE TITLE
Access using default PAUSER  value when CPTRA_MBOX_VALID_PAUSER values are not default 

### ISSUE THREAD

**Issue by nimrodpeled** [chipsalliance/caliptra-rtl#443]
SOC can access internal MBOX registers when using default PAUSER value (0xFFFFFFFF) although the CPTRA_MBOX_VALID_PAUSER is configured and CPTRA_MBOX_PAUSER_LOCK is set.
Test scenario: CPTRA_MBOX_VALID_PAUSER[0-4] are assigned values, say, 0x1, 0x2, 0x3,0x4 and 0x5 respectively and all locks are set to ‘1’ in CPTRA_MBOX_PAUSER_LOCK[0-4] registers to enable these PAUSER values. SOC can still access the MBOX register with default PAUSER (0xFFFF_FFFF)

**Comment by Nitsirks** [comment]
The parameter assigned to default pauser is always valid. We may need to update the documentation to make this more clear.

**Comment by bharatpillilli** [comment]
@Nitsirks - close this?
