### ISSUE TITLE
Caliptra LINT Violations

### ISSUE THREAD

**Issue by mborder-amd** [chipsalliance/caliptra-rtl#445]
Summary of Caliptra LINT violations attached. Several LINT issues have been addressed with RTL->RTL Formality LEC passing. Details can be found in the attachment. This issue will be used to create a PR for review.

[Caliptra LINT Summary 2024.02.29 - PR.pdf](https://github.com/chipsalliance/caliptra-rtl/files/14453061/Caliptra.LINT.Summary.2024.02.29.-.PR.pdf)

**Comment by steven-bellock** [comment]
![image](https://github.com/chipsalliance/caliptra-rtl/assets/8474235/0d83864c-764c-4936-835e-d50219c1cfc3)

Those are parameters, not signals though : https://github.com/chipsalliance/caliptra-rtl/blob/8c11e4695308a233b2332737b9d41ea297be5b52/src/riscv_core/veer_el2/rtl/el2_param.vh#L18 They should be two state.

**Comment by calebofearth** [comment]
Resolved by #483
