### ISSUE TITLE
Mailbox flow not working when we do backdoor load of memory and do frontdoor read of dataout through register.

### ISSUE THREAD

**Issue by tnsri** [chipsalliance/caliptra-rtl#450]
Hi,

When we are trying to do backdoor loading of memory and try to read the same through register frontoor read , we see that the mbox_rdptr_nxt is not getting incremented as that is getting incremented on the writes which are doing through the datain register based on that dlen is getting incremented, it is not working with backdoor write as dlen will not be getting incremented, can you please confirm is there is any way to do it through backdoor loading and frontdoor reading.

Thanks,
Navya.

**Comment by Nitsirks** [comment]
This is not possible. Mailbox API needs to be followed.
