### ISSUE TITLE
IDEVID Certificate Signature

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#451]
In IDEVID Certificate Table-7 of Caliptra main spec, there is field Signature Value with value as Digital signature for the certificate.
https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#idevid-certificate
1] What values from the Table-7 are taken to generate this Digital signature for the certificate?
2] Are these values hashed and along with the public-key generated in IDEVID DICE flow (Figure 4: DICE Cert/Key generation) used for this signature generation?

Please confirm.

**Comment by varuns-nvidia** [comment]
1) it would be all of them as defined in https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.1.3 as they're all part of the `tbsCertificate`
2) Yes as per above
