### ISSUE TITLE
How IDEVID MANUF HSM IDENTIFIER is used to reconstruct certificate?

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#457]
It is mentioned in CAliptra main spec:
Caliptra does not allocate fuses in its fuse map for the IDevID certificate signature. Caliptra allocates "IDEVID MANUF HSM IDENTIFIER" fuses that the vendor can use to aid certificate reconstruction.

How IDEVID MANUF HSM IDENTIFIER is used to reconstruct certificate?

Regards
Rahul

**Comment by varuns-nvidia** [comment]
All of those fuses are not consumed by Caliptra. They are allocated spares. The vendor can put whatever they want in those fuses.

**Comment by RJMJJJ** [comment]
But what is the procedure how IDEVID MANUF HSM IDENTIFIER is used to reconstruct certificate? Is there any software code that can be referred where IDEVID MANUF HSM IDENTIFIER is used?

**Comment by varuns-nvidia** [comment]
Referencing the LDevID certificate template generation code is a good starting point https://github.com/chipsalliance/caliptra-sw/blob/bcfef10cea57c586e27696288bc1899ccf065f3e/x509/build/build.rs#L51

As an example of why IDEVID MANUF HSM IDENTIFIER exists: potentially a Vendor uses different HSMs for different manufacturing assembly/test lines of the same product. These HSMs might not share identities, so their subject name may be different. The fuse can be used to store the HSM subject name that was used to manufacture the part in question.

**Comment by RJMJJJ** [comment]
Hi

Thanks for reply.
I understand what possibly IDEVID MANUF HSM IDENTIFIER could be. 
Caliptra doc mentions --> IDEVID MANUF HSM IDENTIFIER can be used to aid certificate reconstruction.
Question is how the IDEVID MANUF HSM IDENTIFIER is used to reconstruct certificate.
In the link that you have shared just above function to Generate Local DeviceId Certificate Template, this does not specify or use IDEVID MANUF HSM IDENTIFIER.

**Comment by varuns-nvidia** [comment]
Because IDevID is vendor defined. A vendor can define IDevID such that there's no need to use any fuse bits of IDEVID MANUF HSM IDENTIFIER.

**Comment by RJMJJJ** [comment]
If Caliptra doc mentions it can be used, then how it can be used?

**Comment by varuns-nvidia** [comment]
I think I've answered that question here.
* It is vendor-defined, Caliptra does not provide constraints
* An example is to encode the subject name of the provisioner CA.

**Comment by RJMJJJ** [comment]
My understanding, your answer this and earlier is about what is IDEVID MANUF HSM IDENTIFIER and it is not mandatory to use. My question is about if doc mentions it can be used to reconstruct the certificate, then how it can be used. We are planning to use Caliptra. In certificate recreation clarity on what is the role of IDEVID MANUF HSM IDENTIFIER would have been good to understand as doc mentions it can be used. But wrt answers so far instead of finding hoiw it can be used I would conclude it need not be used.

**Comment by varuns-nvidia** [comment]
Yes, that is the intention of the term "can". It is not "shall" or "should".

**Comment by RJMJJJ** [comment]
I understand but if can then how is valid curiosity. Anyways thanks for replies.

**Comment by varuns-nvidia** [comment]
Yes and thank you for the questions. There is just a limit to what we can put in a specification because it is normative text.
