### ISSUE TITLE
Integration requirement: SoC shall input clock before calitpra_pwrgood assertion

### ISSUE THREAD

**Issue by DerekWangScaleflux** [chipsalliance/caliptra-rtl#458]
Hi, Caliptra team,
      In the Caliptra integration spec: 
   
![image](https://github.com/chipsalliance/caliptra-rtl/assets/127370484/6bc56434-dff7-49ad-b52c-a0ba301e6189)

       Here, "caliptra_pwrgood assertion" means caliptra_pwrgood == 1, right ?
       Why here input clock should be present before caliptra_pwrgood assertion ?

       Normally, clocks will be present after a certain time of power-on-reset. 
       Is there a particular usage here ?

Best Regards
Derek Wang

**Comment by bharatpillilli** [comment]
Requirement is clock is already toggling before the caliptra_pwrgood is asserted (without clock toggling, this signal will not reset certain logic/flops correctly).

**Comment by DerekWangScaleflux** [comment]
> Requirement is clock is already toggling before the caliptra_pwrgood is asserted (without clock toggling, this signal will not reset certain logic/flops correctly).

Hi @bharatpillilli ，
     Thanks.
     This means there are logics/flops with only synchronous reset ?
     Could you list the hierarchy of the logics/flops ?

Best Regards

**Comment by bharatpillilli** [comment]
Flops reset async. We used to have some fsm logic on pwrgood(means used to require clocks) but Mike corrected me that we moved it after caliptra_rst_b dessertion. All that said, it's still a good hygiene to provide clocks before asserting pwrgood (which is reset exit aka coming out of reset)

**Comment by DerekWangScaleflux** [comment]
Hi @bharatpillilli ,
      Thanks. Is there a miminum requirement of how many cycles should be toggling before the caliptra_pwrgood is asserted ?

**Comment by DerekWangScaleflux** [comment]
> Hi @bharatpillilli , Thanks. Is there a miminum requirement of how many cycles should be toggling before the caliptra_pwrgood is asserted ?

Hi @bharatpillilli , 
     Any update on how many cycles should be toggling before the caliptra_pwrgood is asserted ?

Best Regards
Derek Wang

**Comment by calebofearth** [comment]
@DerekWangScaleflux we've updated the specification - please check https://github.com/chipsalliance/caliptra-rtl/pull/571.
