### ISSUE TITLE
Observing mismatches in values captured in log vs waveform for doe rand testcase

### ISSUE THREAD

**Issue by tnsri** [chipsalliance/caliptra-rtl#472]
Hi,

We are trying to run smoke_test_doe_rand testcase and we are observing that the values which are seen in sim log are not matching the values from waveform and are also mismatching with the expected values which we are generating through .doe_test_vector.py file.

![image](https://github.com/chipsalliance/caliptra-rtl/assets/152272534/a4868e8e-5ce2-479d-a6fc-0e6b947a4884)
![image](https://github.com/chipsalliance/caliptra-rtl/assets/152272534/86a31c6a-b349-40dc-a169-ae5738f9ee8d)
deobfuscated value of UDS is stored in KV3 and here we see that the data inside KEY_ENTRY[3][11] to KEY_ENTRY[3][4] is getting captured correctly in logs for output the rest locations are not getting captured correctly inside logs, same behaviour we are seeing for Field entrpy also first 4 DWORDS are getting captured correctly whereas the last 4 DWORDS are not captured incorrectly, can you please confirm if any other configurations needs to be enabled for this , kindly comment on this issue.

Thanks,
Navya

**Comment by Nitsirks** [comment]
I am not able to recreate this issue in our environment.

Does this test fail every time, or was it just this particular set of test vectors that mismatched?

**Comment by tnsri** [comment]
Yes , everytime it fails .

**Comment by Nitsirks** [comment]
We're not able to reproduce this failure in our environment.

Are you running on caliptra_top_tb?

**Comment by tnsri** [comment]
Yes running on caliptra_top_tb , and the test vectors are generating through  .doe_test_vector.py file.

**Comment by tnsri** [comment]
Can you please let me know if im missing on any thing, updating the steps below which im doing
->copying the doe_test_gen.py to the sim area
->executing make script for program.hex generation
-> updating $system("python3 doe_test_gen.py"); with python3 version
->make script for simulation

**Comment by Nitsirks** [comment]
Can you attach logs from the simulation, and the generated doe test vector file? That might help me reproduce it on our end.

**Comment by tnsri** [comment]
please find the doe_test_vector.txt file generated

2f5c9f67039ed245c67dfce7482498fb93c7e52111f497d1abaa2b3d35db8e36
e717334a7e82fa18580e158304ddf891
c0d34baf2b9b923bb7f705d3d92344db03d860835eafba2ea1350e3b65e61d9506f731c069f70883172a1d97442115ef
0f468d9106b9b97f905ba4c06e0ca79efb624407281ed50132ef0a1851a0384736db73bfb24a60dd30d5e450e65eeac1
2f5c9f67039ed245c67dfce7482498fb93c7e52111f497d1abaa2b3d35db8e36
2a9a9138d13e772b3baf12cf1a9c5143
58751f41f30094c19c1a53b1064efc0609b9f4758f31579164bb75c4875602fa
784b2244ab88ee79863081a0adcb7db9ffdd68a41a4f3dcdeb68f4f660cefbe1

**Comment by Nitsirks** [comment]
I ran with this set of generated vectors and everything passes. I did some sanity checks and confirmed the values by inspection too. Do other tests pass in your environment?

You'll need to do some debug on your end. First confirm that doe block is getting the correct values for obf key, uds, and IV. If those are correct, the output from DOE should be correct.
