### ISSUE TITLE
itrng_valid rate higher than 50KHz

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#475]
In Caliptra Hardware Spec in Physical true random noise source signal descriptions section it is mentioned

**itrng_valid | input | Valid is asserted high for one cycle when data is valid. The expected valid output rate is about 50KHz.**

Is this 50KHz rate for itrng_valid is mandatory requirement? We are getting it at higher rate of 81.2 KHz from the TRNG IP available with us, will it work or there will be issue. 

If you can elaborate on possible issue it will be helpful.

Regards

**Comment by bharatpillilli** [comment]
@howardtr  can comment. What is listed in the spec is to which what we have validated to and thereby recommended. Outside of it is at your own validation.

**Comment by howardtr** [comment]
81.2khz  will be fine.  There's a small fifo inside the design that will process (via health checks) and store the incoming entropy.   If the fifo fills up, it will drop the extra entropy before entering the conditioner.

But yes - please verify on your end as well

**Comment by RJMJJJ** [comment]
Thanks for the response. We will check at our end as well as suggested.

**Comment by bharatpillilli** [comment]
FYI, Luke from FPGA team validated multiple sampling rates too.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/BPILLI~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/BPILLI~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/BPILLI~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



ITRNG   divider | Equivalent   ITRNG data rate
-- | --
2 | 200Mhz
40 | 10Mhz
400 | 1Mhz
4000 | 100Khz
8000 | 50Khz




</body>

</html>
