### ISSUE TITLE
[MBOX] dlen restricts size of data response that may be read

### ISSUE THREAD

**Issue by calebofearth** [chipsalliance/caliptra-rtl#48]
In the Mailbox protocol, the mbox_dlen register is used to restrict whether rdptr is allowed to increment or not, and thus controls how much data can be read from mbox_dataout.
Response data may realistically be larger than original request data, so restricting readout by mbox_dlen will hide some of the response.

The suggested fix is two pronged:
1. A receiver of a mailbox command is allowed to write a new value to the mbox_dlen register. The new value corresponds with response data size. Only uC will ever post response data to a mailbox command, so in practice this means that mbox_dlen writes are enabled when the FSM is in EXECUTE_UC state.
2. To mitigate potential security holes, implement a flop stage in the mailbox that captures mbox_dlen on state transitions. The mailbox command recipient will only be able to read from mbox_dataout in the amount reflected in the flop-stage, but the command recipient will be able to write a new mbox_dlen value (which will be used to restrict reads from mbox_dataout of the response data by the original requester, i.e. SOC).

**Comment by korran** [comment]
FWIW, in my testing with the verilator model, it seems like the uC is able to set dlen as part of the response.

**Comment by anjpar** [comment]
Closing issue. Fixed with rev 0p8 release #49
