### ISSUE TITLE
Question of CDC requirement on input port, GENERIC_INPUT_WIRES[ 63:0 ]

### ISSUE THREAD

**Issue by DerekWangScaleflux** [chipsalliance/caliptra-rtl#487]
Hi Caliptra team，
        In the integration spec for generic_input_wires:
![image](https://github.com/chipsalliance/caliptra-rtl/assets/127370484/bf94f738-77e4-437b-8a7e-46b5670d5a43)

        "generic_input_wires" are 64-bit and is required to be sync with caliptra clk.
         But how to sync these signals from SoC clock to caliptra clk ? There are no handshake interface related to it.
         Or it will be used as only 1-bit toggling at one time ？

Best Regards
Derek Wang

**Comment by calebofearth** [comment]
Hi Derek, 

Please refer to [Late Binding Interface Signals](https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md#late-binding-interface-signals).
Only one bit from the generic input wires is currently in use (as of 1.0 version). It should be synchronized continuously using a level synchronizer from the SoC status indicator. The other 63 bits should be tied to 0.
