### ISSUE TITLE
TAP Sequence reference for RISC-V Debug

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#500]
Can you please share any TAP sequence references for RISC-V Debug through JTAG from external Debugger?

**Comment by calebofearth** [comment]
There are some tests that perform JTAG flows defined in https://github.com/chipsalliance/caliptra-rtl/blob/main/.github/workflows/interactive-debugging.yml, can you review these to see if they address your question?
