### ISSUE TITLE
Change DRBG from SHA-2-384 to SHA-2-512 used in the ECC Key Derivation

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-rtl#526]
The DRBG used within Caliptra needs to be changed from SHA-2-384 to SHA-2-512.  Tests must be updated to meet the new requirements.

**Comment by bharatpillilli** [comment]
Not an option for 1.x; this is a 2.0 topic given where we are.

**Comment by bharatpillilli** [comment]
@mojtaba-bisheh to look into this for 2.0 and we will mark it approved after the analysis

**Comment by mojtaba-bisheh** [comment]
@bharatpillilli Since CMVP removed the prohibition of using SHA2-384 for DRBG, and based on our discussion about DICE key derivation, we can close this issue.

**Comment by bharatpillilli** [comment]
@mojtaba-bisheh - assuming still not needed, cross check me.

**Comment by mojtaba-bisheh** [comment]
correct, DRBG SHA2-512 is not needed

**Comment by bluegate010** [comment]
I will note that from what I heard, NIST may be interested in removing allowance for SHA2-384 DRBG in the future, but that is at an indeterminate time, they will have a longer grace period, and there is room to get approval based on the narrow DICE use-case.
