### ISSUE TITLE
kv_reg implementation utilizes a lot of logic resources

### ISSUE THREAD

**Issue by jlmahowa-amd** [chipsalliance/caliptra-rtl#53]
These numbers are from integrating Caliptra for FPGA, however the size concerns may still impact ASIC due to die area.
![fpga_utilization_dev-msft_20230331](https://user-images.githubusercontent.com/102375203/229838223-14291642-97c4-456c-8193-335d8fcc3207.PNG)

kv_reg accounts for approximately a quarter of the logic utilization of Caliptra for FPGA. kv_reg contains a similar amount of data to pcr_vault (32x48 byte keys) but it consumes 5x more logic resources. kv_reg is an outlier regarding logic utilization.
SRAMifying that logic was considered in the past, and may need to be reconsidered. For FPGA this increases risk of needing to upgrade to a larger, less available board. For ASIC this impacts die area and cost.

**Comment by Nitsirks** [comment]
I don't think SRAM is the solution. PCR and Key vaults have roughly the same amount or storage - I imagine it's the read/write combo logic that is blowing up. 

We've identified at least one read/write path that is unnecessary and is being removed now, which should help. If it continues to be a problem, I think we can reduce the logic here by changing up the micro-architecture a bit. I'll look into some options.

**Comment by bluegate010** [comment]
24 KV slots are currently reserved for DPE. If FIPS weren't a concern we could get by with 1 or 2. We _could_ be less conservative and allocate only 8-12 or so for DPE. The impact would be how many concurrent DPE contexts we can safely handle. Current use-cases only call for 2-3 max identities at any one time, so we could probably reduce.

**Comment by bharatpillilli** [comment]
This is already a committed feature for 32 key slots and PCR slots. In order to make progress, we aren't going to make any changes - closing the issue.
