### ISSUE TITLE
Feature Request: move OWNER_PK_HASH to a register

### ISSUE THREAD

**Issue by varuns-nvidia** [chipsalliance/caliptra-rtl#540]
With OCP Device Ownership Transfer, the SoC Manager ROM needs to perform some logic to determine the owner key. This is tough to reconcile with Caliptra’s requirement that the owner key hash be provided by fuse done.

Request is to replace fuse_owner_pk_hash with a SoC Manager programmable and lockable register.

Caliptra HW requirements:
1. Hash bits on cptra_pwrgood reset
2. Lock bit on cptra_pwrgood reset
3. Caliptra access: RO
4. SoC access: RW, Read-Only once locked

Caliptra ROM requirements:
1. Move OWNER_PK_HASH reads to the new register.
2. Read the register as part of Caliptra FW_LOAD command servicing. Copy it into Data Vault prior to consumption to avoid any potential time-of-check-to-time-of-use issues.
3. Attest to the lock bit in PCR0 and in DiceTcbInfo of AliasFMC, replacing the existing boolean of whether the owner pk hash in fuses is 0

SoC Manager requirements:
1. If applicable, SoC Manager must program OWNER_PK_HASH and LOCK bit prior to issuing Caliptra FW_LOAD command.

**Comment by calebofearth** [comment]
Closed by #640
