### ISSUE TITLE
Synchronicity of JTAG reset

### ISSUE THREAD

**Issue by steven-bellock** [chipsalliance/caliptra-rtl#545]
The integration specification says

Signal name | Width | Driver | Synchronous (as viewed from Caliptra’s boundary)
-- | -- | -- | --
jtag_trst_n | 1 | input | Async Deassertion<br/> Assertion Synchronous to tck

However the JTAG reset has asynchronous assertion and (ideally) synchronous deassertion. From 1149.1
>If TRST* is included in the TAP, the TAP controller and TMP controller shall be asynchronously reset to the Test-Logic-Reset and Persistence-Off controller states, respectively, when a logic 0 is applied to TRST*...

Note that 1149.1 doesn't say how `TRST*` should be deasserted but most folks deassert it synchronously to the falling edge of `TCK`.

**Comment by steven-bellock** [comment]
@calebofearth you can assign this to me as I already have a pull request for it.

**Comment by calebofearth** [comment]
Thanks @steven-bellock, I merged this in for the 1.1 release.
