### ISSUE TITLE
Replace APB with AXI Sub and remove the need for SOCs to gasket APB<->AXI

### ISSUE THREAD

**Issue by bharatpillilli** [chipsalliance/caliptra-rtl#563]

**Comment by morris-c-mao** [comment]
Is it possible to have the interface configurable by parameter or define?
Some SoC system bus is AXI; some are AHB or bridging to APB.

**Comment by calebofearth** [comment]
> Is it possible to have the interface configurable by parameter or define? Some SoC system bus is AXI; some are AHB or bridging to APB.

@morris-c-mao there is no current plan to support both modes. Gen2 will only support the AXI interface.
