### ISSUE TITLE
Add AXI manager and DMA capability support for Active Caliptra mode

### ISSUE THREAD

**Issue by bharatpillilli** [chipsalliance/caliptra-rtl#564]

**Comment by calebofearth** [comment]
The following should be added to the Integration spec:
In Active Mode, Caliptra can use the SHA Accelerator via DMA block by initiating AXI-to-AXI transfer to the SHA accelerator. Access is protected by an AXI ID filter.
In Active Mode, SHA Accelerator may only be used by Caliptra and is unavailable to the rest of the SoC.
