### ISSUE TITLE
[FIPS] SHA Mailbox Capability Enable/Disable Bit

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-rtl#58]
# Requirement Origin
Based on FIPS requirements, a module cannot provide any crypto functionality until it is fully initialized.  Also, another FIPS requirement requires that all crypto functionalities be disabled when the module is in an error state.  Therefore, FW will need to disable this functionality when an error has occurred.

# Requirement
Caliptra requires an enable bit on the FW side to enable/disable this functionality on demand with the default for this functionality to be disabled.  We will also require a FIPS Status Indicator return status to indicate that the operation is FIPS approved.

**Comment by bharatpillilli** [comment]
Hi John - Can you please bring it to TAC for approval? Here is the process steps -> https://github.com/chipsalliance/caliptra-rtl/issues/43

**Comment by JohnTraverAmd** [comment]
Yes.  Will do.

**Comment by JohnTraverAmd** [comment]
This command will also require a status indicator and KAT.

**Comment by JohnTraverAmd** [comment]
**SHA SOC Disabled:** We could set the default to locked for this HW.  And the lock owner will be Caliptra and this will show in the status field.

**FIPS Status Indicator**: Can we define the lock as 0 if it is approved, or using a bit in the status register to indicate that it was approved.

Caliptra FW won't release the lock to the SOC until after Caliptra FW has been provided, authenticated and executed.

**TBD:** ROM could have a NON-FIPS parameter where it does unlock it after the KAT so that some customers could use the HW before FW is loaded.  TBD.

**Comment by bharatpillilli** [comment]
Lock is set by default and biased to uController; STATUS already reports SOC_HAS_LOCK => LOCK=1 and SOC_HAS_LOCK=0 => SOC cannot use it until uController runs FIPS and unlocks.

Test cases verified
- SHA512 Acc is locked by default at reset; requires explicit unlocking
- SHA512 Acc can be used by uController right out of reset without locking because its biased to uController!
- SHA512 Acc being unlocked by uController val ROM FW before SOC side can use it

**Comment by JohnTraverAmd** [comment]
Can we enable this once ROM has authorized the FW?

**Comment by JohnTraverAmd** [comment]
For the status indicator, it is required that the FW is able to set a bit in a register which indicates that the FIPS KAT passed.  This will be the FIPS approved indicator.  This will need to writable ONLY by the Caliptra side and will need to be visible to the SOC side.  This will need to initialize to non-approved and be able to be set by FW to indicate that it is now approved once the KAT is passed.

**Comment by bharatpillilli** [comment]
> Can we enable this once ROM has authorized the FW?

It is upto ROM when it wants to unlock

**Comment by bharatpillilli** [comment]
> **FIPS Status Indicator**: Can we define the lock as 0 if it is approved, or using a bit in the status register to indicate that it was approved.

From the above comment - "FIPS Status Indicator: Can we define the lock as 0 if it is approved, or using a bit in the status register to indicate that it was approved." - picked the lock as the status indicator as it was the natural status.

**Comment by bharatpillilli** [comment]
@JohnTraverAmd - plz confirm my above statement....if agreed, the fix is already in the ToT, else would have to make changes.

**Comment by bharatpillilli** [comment]
@JohnTraverAmd ??

**Comment by JohnTraverAmd** [comment]
I'm working with the FIPS team to identify.  We'll respond by today.

**Comment by bharatpillilli** [comment]
Any update @JohnTraverAmd ?

**Comment by JohnTraverAmd** [comment]
Yes. There is no further work required here.

Thank you,

John
