### ISSUE TITLE
Extend Fuse/FE to 512-bits, Update HMAC384 to HMAC512 to meet PQC ML-DSA-87 requirement 

### ISSUE THREAD

**Issue by mojtaba-bisheh** [chipsalliance/caliptra-rtl#581]
[FIPS204 ](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.204.pdf) requires using SHA512 for pre-hash mode to maintain security level at category 5. 
[IETF Composite Keys and Signatures draft](https://github.com/lamps-wg/draft-composite-sigs/tree/main) requires using SHA512 for hybrid mode between ML-DSA-87 and ECC Secp384r1.

Hence, HMAC384 needs to be updated to HMAC512 to maintain PQC flow at category 5. HMAC384 will be removed.

Since HMAC512 requires 512-bit key, UDS and FE needs to be extended to 512 bits.

KV needs to be extended to 512 bits as mentioned here: https://github.com/chipsalliance/caliptra-rtl/issues/580

Since PCR path needs to be implemented within hardware boundary, any IETF requirement for hybrid signature will be hardcoded.

**Comment by calebofearth** [comment]
Addressed in #625 and https://github.com/chipsalliance/caliptra-rtl/pull/589

**Comment by mojtaba-bisheh** [comment]
We support dual signatures, and FW/SW will be responsible for using composite signature or any other hybrid schemes
HMAC supports both HMAC384 and HMAC512.
PCR path will be addressed as a part of https://github.com/chipsalliance/caliptra-rtl/issues/645
