### ISSUE TITLE
[FIPS] ROM Integrity Check BIST

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-rtl#59]
# Requirement Background

- 5.06
-- A cryptographic mechanism using an approved integrity technique or an error detection code (EDC) shall  be applied to all software and firmware components within the hardware module’s defined cryptographic boundary or within disjoint hardware components of the hybrid module.
- 5.07
-- Regarding 5.06, if an EDC is used, the EDC shall be at least 16 bits in length
- 10.01-10.02
-- All self-tests shall [10.01] be performed, and determination of pass or fail shall [10.02] be made by the module, without external controls, externally provided input text vectors, expected output results, or operator intervention or whether the module will operate in an approved or non-approved mode.
- 10.03
-- The pre-operational self-tests shall be performed and passed successfully prior to the module providing any data output via the data output interface.
- 10.53
-- A cryptographic module shall permit operators to initiate the pre-operational or conditional self-tests on demand for periodic testing of the module.

# Requirement Description
- Read entire ROM from 0 to N-2 performing a CRC32 operation.  Compare the result with N-1 location of the ROM.  It should be identical.
- If it is identical, then the BIST passes, if it is not, then it fails.
- FW should have a register to read the result of the most recent BIST, which may be the initial BIST that executed on reset exit
- CRC32 is all that is required for this operation.  Anything more secure than CRC32 would also be acceptable.
- Upon failure out of reset, Caliptra would enter a failure state.
- Upon failure after reset, an error bit would be indicated in the register and FW should be informed.  FW then can take action based on policy.

# Requirement Notes
- If the ROM is maskable from general FW, this ROM BIST must be able to access it even when FW is masked to verify integrity.
- At reset, this is performed before the CPU begins executing.  This must pass for execution if FIPS KATs are required.

**Comment by JohnTraverAmd** [comment]
Will take this to TAC

**Comment by bharatpillilli** [comment]
Hi @JohnTraverAmd - Didn't we already discuss this and was deemed not necessary or be will be done using FW in discussions with [nstewart-amd](https://github.com/nstewart-amd)?

**Comment by JohnTraverAmd** [comment]
Hi @bharatpillilli, - This is the better long-term solution since ROM doing this will add to boot-time and there is desire that the ROM access be disabled to FW.  We may decide that in the short-term the ROM would still perform this.

**Comment by JohnTraverAmd** [comment]
This will be rejected if we approve https://github.com/chipsalliance/caliptra-sw/issues/313

**Comment by bharatpillilli** [comment]
Closing this issue as any RTL change here is too late for Gen 1 anyways!
