### ISSUE TITLE
Register type RWL-S are NOT locked after the first write

### ISSUE THREAD

**Issue by lindadong919** [chipsalliance/caliptra-rtl#596]
Hello,

Our test found the RWL-S type registers are writable more than once, e.g. fuse_key_manifest_pk_hash[], fuse_owner_pk_hash, fuse_idevid_cert_attr[], fuse_idevid_manuf_hsm_id[], fuse_fmc_key_manifest_svn, fuse_runtime_svn[], fuse_lms_verify, fuse_lms_revocation, fuse_soc_stepping_id, fuse_life_cycle. 

Can you please take a look? 

Thanks,
Linda Dong

**Comment by calebofearth** [comment]
Hi Linda,

This is the intended behavior. These registers are designed to be "lockable", but not write-once. ("RWL-S" stands for Read-Write-Lock--Sticky). During the boot flow, SoC shall populate the fuses and then set the fuse wr done bit, as described in the Integration spec and in the [CPTRA_FUSE_WR_DONE](https://chipsalliance.github.io/caliptra-rtl/main/external-regs/?p=caliptra_top_reg.generic_and_fuse_reg.CPTRA_FUSE_WR_DONE) register. Setting CPTRA_FUSE_WR_DONE locks the fuses from any subsequent writes until cold reset.

I do see an ambiguous statement in the Integration spec ([here](https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md#fuses)) that should be clarified. The intent is that Fuses are only programmable at a specific stage during boot up, and never again during runtime. I submitted a PR to clarify the spec.

**Comment by lindadong919** [comment]
Hi Caleb,

Thank you very much for your quick response. I understand the function now.

Regards,
Linda
