### ISSUE TITLE
add a protection for intermediate states in SHA save/restore feature

### ISSUE THREAD

**Issue by mojtaba-bisheh** [chipsalliance/caliptra-rtl#601]
it would be interesting if we can seal the intermediate states so external world cannot tamper the intermediate state.

**Comment by bharatpillilli** [comment]
Another feature exists like this? @mojtaba-bisheh close this?

**Comment by mojtaba-bisheh** [comment]
no similar feature. however, we've discussed and realized this feature will not be required for SHA operation since there is no secret involved.
FYI @swenson
