### ISSUE TITLE
Do you have plan to change JTAG 5pins to 2pins?

### ISSUE THREAD

**Issue by byunggu-jo** [chipsalliance/caliptra-rtl#604]
Hi, 
I can check caliptra JTAG is use legacy 5pins JTAG.
Because of my SoC use 2pin, I need find method of connect 5pin JTAG and 2pin JTAG for use same PAD.

Do you have plan to change JTAG 5pin to 2pin at later version?
If yes, can I know which version and plan to release date?

Thank you.

**Comment by bharatpillilli** [comment]
No
