### ISSUE TITLE
Write '1' won't clear sha512_acc_csr.LOCK

### ISSUE THREAD

**Issue by lindadong919** [chipsalliance/caliptra-rtl#606]
Hi,

We are writing to sha512_acc_csr.LOCK and found that it didn't clear the LOCK. I did a bit of tracing and found the following code:
 // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

As you can see when cpuif_req is asserted, cpuif_req_masked is always asserted because cpuif_req_stall_rd and cpuif_req_stall_wr is '0'. In turn, the decoded_reg_strb.LOCK is alwasy return '1'.

Can you please take a look?

Thanks,
Linda D

**Comment by Nitsirks** [comment]
If I recall off the top of my head, there is a FIPS requirement that the accelerator has to start locked by Caliptra. Only after Caliptra has performed necessary KATs can the lock be released.

I assume you are trying to release the lock from the SOC side?

**Comment by lindadong919** [comment]
Thanks for the info. Yes, I was trying to release the lock from SOC side. 

Regards,
Linda
