### ISSUE TITLE
Figures with no text

### ISSUE THREAD

**Issue by hakimahunov** [chipsalliance/caliptra-rtl#63]
Hi everyone,

first of all, thank you, guys, for making such a project open-sourced.
Recently, I started to discover the Caliptra project and its specifications, especially related to RTL, and notices that many figures in the documents are not complete. There is no text on them, only blocks. For example:
![image-1](https://user-images.githubusercontent.com/11958591/231751716-d12fdca8-8559-42c3-af39-dfd78e34a11e.png)
![image-2](https://user-images.githubusercontent.com/11958591/231751758-d076169a-6ae6-49d1-bcfe-4860cd99a2ee.png)

and many others.

It seems like an issue with PDF conversion. Is there a chance to upload the specifications with complete images?

Many thanks!

Best regards
Khakim

**Comment by bharatpillilli** [comment]
@anjpar fixed it with recent PR
