### ISSUE TITLE
FIPS Status and Version Information Reporting

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-rtl#65]
FIPS requires the following information:

- Version
- Mode of operation
- Status Indicator of APIs
- This may require a new HW register or an expansion of the status command.

Details for this will be completed when we get FIPS consultation.

**Comment by JohnTraverAmd** [comment]
This is trending to be completed only by FW based mailbox commands.

**Comment by JohnTraverAmd** [comment]
John to clearly define this command and ensure that it meets all requirements and that no additional HW is required.

**Comment by bharatpillilli** [comment]
Closing this as there is no HW change needed for this and can be done using mailbox commands
