### ISSUE TITLE
watchdog timer mismatched write access in soc rdl

### ISSUE THREAD

**Issue by howardtr** [chipsalliance/caliptra-rtl#68]
Ran into an error with the soc ifc rdl while trying to update dev-goog.  Re-ran the following action against dev-msft:
https://github.com/chipsalliance/caliptra-rtl/actions/runs/4792143932/jobs/8523320077

It looks like there may be some sw read only fields defined that are conflicting with the swwel setting, which were added recently with the watchdog timer changes https://github.com/chipsalliance/caliptra-rtl/commit/51bf68d3c2e3a1499f53d31b1b45f144726041aa#diff-ada1721e8b45427d0903e9a396a2dc6fb6269b83d46c62403bc6c363b950631f

```
src/soc_ifc/rtl/soc_ifc_external_reg.rdl:246:24: error: Field's software access is 'sw=r' but property 'swwel' implies it can be written in some situations during runtime.
    field {sw=r; hw=r; swwel = soc_req; resetsignal = cptra_rst_b;} REV_ID[32]=1;
                       ^^^^^
src/soc_ifc/rtl/soc_ifc_external_reg.rdl:323:72: error: Field's software access is 'sw=r' but property 'swwel' implies it can be written in some situations during runtime.
    field {desc = "Timer1 timed out, timer2 enabled"; hw = rw; sw = r; swwel = soc_req; resetsignal = cptra_rst_b;} t1_timeout = 1'b0;
                                                                       ^^^^^
src/soc_ifc/rtl/soc_ifc_external_reg.rdl:324:56: error: Field's software access is 'sw=r' but property 'swwel' implies it can be written in some situations during runtime.
    field {desc = "Timer2 timed out"; hw = rw; sw = r; swwel = soc_req; resetsignal = cptra_rst_b;} t2_timeout = 1'b0;
                                                       ^^^^^
```

Sending out for the team to review since I'm not aware of the intended behavior

**Comment by anjpar** [comment]
@howardtr I am investigating this now.
