### ISSUE TITLE
"Current PCRs" cannot be locked until next Caliptra warm reset

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-rtl#76]
This leaves these PCRs open to erasure by runtime firmware. Hardware PCRs that are freely erasable by firmware do not have sufficient value as a store of measurements.

Either RTL should support an extra warm reset domain for PCR locking, or "current PCRs" should be retired as a concept.

**Comment by bharatpillilli** [comment]
"Lock" will not allow FW to clear. Lock will still allow you to extend the PCR. Its already in the RTL

![image](https://user-images.githubusercontent.com/7234606/235246906-b0d9ead7-596e-40e1-8670-f6dc3baef753.png)

**Comment by bluegate010** [comment]
What I mean is that a PCR can only either be locked or unlocked, there's no in between.

* Locked: cannot be cleared until a power cycle.
* Unlocked: can freely be erased by runtime firmware.

An unlocked PCR is not a safe place to put runtime firmware measurements if you're worried about runtime firmware lying to you. And a locked PCR is only suitable for a "journey" PCR, not a "current PCR".

**Comment by bharatpillilli** [comment]
If current is erased, because PCR signing is done by HW with the key that is 'locked' by ROM - what is present in PCRs is what is signed! So even FW lied, the signing cannot be fooled

**Comment by bluegate010** [comment]
But FW can replace the contents of "current" PCR with whatever FW wishes, then allow HW to sign the FW-controlled PCR contents. So we have ROM and FMC extending measurements into a "journey" PCR, with the assumption that HW-generated quotes will contain an accurate reflection of the measurements that ROM and FMC actually captured. But there's no guarantee of that. FW is free to replace the measurements that ROM and FMC extended.

So even though HW can emit an honest quote of the value of these PCRs, no one should be making security decisions about those unlocked PCRs' values if they do not already trust FW.

**Comment by bharatpillilli** [comment]
I dont understand that statement - why do we do PCR signing and report PCRs if no one is there on the other side to make decisions on it?

Independent of what Caliptra is doing - a man-in-the-middle can also 'erase'/modify the 'current' PCRs.

I am probably not understanding your view - plz let me know

**Comment by bluegate010** [comment]
Just to summarize the offline discussion - PCRs that can be reset by Caliptra FW are not trustworthy places to hold measurements of Caliptra FW.

**Comment by bharatpillilli** [comment]
Fixed the bug of moving the PCR block to be on core reset/FW update reset domain to account for the case where "RT FW PCR" can also be unlocked/locked. this came up on a different thread.

**Comment by bluegate010** [comment]
Does that mean that the PCRs cannot maintain state across hitless FW updates? Or does it just mean that all PCRs get autonomously unlocked across hitless FW updates, but their value remains the same?

**Comment by bharatpillilli** [comment]
They can - only PCR lock is being reset so that it can be locked!

**Comment by bluegate010** [comment]
Excellent, thanks!
