### ISSUE TITLE
pv_hash_and_sign smoke test failing

### ISSUE THREAD

**Issue by howardtr** [chipsalliance/caliptra-rtl#83]
I was trying to merge in changes from dev-msft (https://github.com/chipsalliance/caliptra-rtl/pull/82), and it looks like pv_hash_and_sign [failed](https://github.com/chipsalliance/caliptra-rtl/actions/runs/4895390302/jobs/8740921093?pr=82)

steps to reproduce:
1. cd caliptra-rtl/
1. git checkout dev-msft
1. git pull
1. git checkout 2a2b1ed27378bbedb3b9acc78f81c0ccd4ee80d7
1. make CALIPTRA_ROOT=../.. clean verilator TESTNAME=pv_hash_and_sign

```
---------------------------
 KV PCR Hash Extend Test !!
---------------------------
PV: prog kv read ctrl in SHA to do hash extend
KV: checking for errors
KV: Writing SHA Block with known answer
KV: Padding extended hash value
KV: polling for sha ready
SHA512: Set mode: 0x2 and init with last
KV: polling for sha valid
KV: polling for kv valid
KV: checking for errors
SHA Result Mismatch - EXP: 0xF57BB7ED RECVD: 0x0
* TESTCASE FAILED
```

**Comment by calebofearth** [comment]
We've had some commits on this test in the last few days, so this may be resolved.
Adding @mojtaba-bisheh as he's been working on this.

**Comment by calebofearth** [comment]
Whoops, sorry, misread the test. This should go to @Nitsirks.

**Comment by Nitsirks** [comment]
I've confirmed that this test passes on verilator 4.228, but fails on 5.002. I suspect it's an issue with verilator, but haven't yet been able to identify the root cause.

**Comment by howardtr** [comment]
There was an interesting update in https://github.com/chipsalliance/caliptra-rtl/issues/79#issuecomment-1540246456

Wondering if there's a subtle force/release that might be causing issues here as well?

**Comment by Nitsirks** [comment]
Good call - we actually saw this issue before with force/release on complex combo logic.

I commented out the force/release on pcr vault signals and the test passes on 5.002 now. I'll see if I can move the force to a signal that works.

**Comment by Nitsirks** [comment]
It looks like repeated "release" calls may be the source of the problem. The tb code was forcing on clocks with a certain write to a control register, and releasing every other clock.

I've submitted a fix that sets a flag whenever we force the signal and uses that flag to release the next cycle only. It's passing on 5.002

**Comment by howardtr** [comment]
Awesome, thanks @Nitsirks

**Comment by howardtr** [comment]
https://github.com/chipsalliance/caliptra-rtl/actions/runs/4984958150/jobs/8924304468
