### ISSUE TITLE
Caliptra RDC violations

### ISSUE THREAD

**Issue by amullick007** [chipsalliance/caliptra-rtl#89]
The RDC analysis and violations have been summarized at [Caliptra_RDC_Analysis.pdf](https://github.com/chipsalliance/caliptra-rtl/files/11502317/Caliptra_RDC_Analysis.pdf)

The detailed list of all paths are attached in the excel file at [RDC_Violations.xlsx](https://github.com/chipsalliance/caliptra-rtl/files/11502318/RDC_Violations.xlsx)

Final decision/conclusion to prevent RDC crossing are summarized as below:-

- Move BootFSM to pwrgood domain
- BootFSM should look at firmware reset assertion and _cptra_rst_b_ assertion to generate an _assert_window_ signal which will be used to gate the clocks of the destination flops
- _assert_window_ from BootFSM will be fed to _caliptra_top.cg.caliptra_icg_ to gate _caliptra_top.clk_cg_
- A new ICG needs to be added for _caliptra_top.rvtop.clk_ whose gating will be controlled by _assert_window_ from BootFSM
- Since _cptra_rst_b_ is going to be used by BootFSM, we should move the reset of the flops which are currently on _cptra_rst_b_ to _cptra_noncore_rst_b_
- BootFSM should delay the assertion of warm reset to ensure that the clock is gated before the assertion edge

In addition to the above, please check the issue listed in Section 6 related to the logic driving _dbg_dm_rst_l_ in Caliptra_RDC_Analysis.pdf

Local RTL changes done at my end are present at https://github.com/amullick40412/caliptra-rtl/commit/bef0ef2a9bd894565cdbb5d30443bf37f79f54cf

**Comment by bharatpillilli** [comment]
Fixes WIP and then we will have more back & forth clean up

**Comment by Nitsirks** [comment]
I have pushed a branch with my WIP so far. I think we should see most of the issues cleared up and want to confirm that.

There are still some bugs/concerns that need ironed out.

michnorris-msft-issue89

**Comment by bharatpillilli** [comment]
https://github.com/chipsalliance/caliptra-rtl/pull/149/ sync to dev-msft should fix non-debug paths of this. Avirup will run RDC to check on it once the sync is complete.
