### ISSUE TITLE
Have ROM lock PCR0 on every boot

### ISSUE THREAD

**Issue by bluegate010** [chipsalliance/caliptra-rtl#90]
As per https://github.com/chipsalliance/caliptra-rtl/issues/76, all PCRs are autonomously unlocked across hitless firmware update. ROM should be sure to lock PCR0 on every boot, not just on cold-boot.

**Comment by bharatpillilli** [comment]
This falls into sw repository as there is no HW change here. @bluegate010  - can u check if this can be moved or filed into that repo and then close this?

**Comment by bluegate010** [comment]
Ah right, this is in the wrong repo. Will re-file.
