### ISSUE TITLE
FIPS Ability to Identify HW Revision

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-rtl#94]
Requirement: The FIPS module needs to version everything to help users match a version with a security policy to verify that the module is correctly validated.  HW must have a version indicated.  Any time a new mask is created for HW, a new version needs to be indicated.

Description: A fuse register will be created for inputing the HW version.  This value needs to be provided to FW for collecting of the versions and reporting on the versions on request.

**Comment by steven-bellock** [comment]
Maybe have the major version embedded in the RTL? Then if there is an ECO-type change then the fuse can be used to indicate that.

**Comment by JohnTraverAmd** [comment]
CPTRA_HW_REV_ID can have a major/minor versions set to it.  The major will be specified by the IP, and the minor can be updated by the integrator at integration time.

This will need to be reved for each stepping.

**Comment by JohnTraverAmd** [comment]
This issue is trending to be an implementation guide update where the CPTRA_HW_REV_ID register will be updated to have major/minor values.  The major will be owned by Caliptra WG and the minor will be updated by the integrator based on HW tape-out.

The Integrator would be required to ensure that the minor version was distinct for each HW revision released.

**Comment by JohnTraverAmd** [comment]
@bharatpillilli was this implemented?

**Comment by upadhyayulakiran** [comment]
Updated reg to contain the following fields:
CPTRA_GENERATION
SOC_STEPPING_ID (written through a fuse upon reset)
