### ISSUE TITLE
All Outputs Disable on Error

### ISSUE THREAD

**Issue by JohnTraverAmd** [chipsalliance/caliptra-rtl#95]
Requirement: FW/HW needs a mechanism which can disable all cryptographic/FIPS sensitive outputs (other than status) from the Caliptra module when an error occurs.  

Description: When an error occurs, all HW outputs related to crypto operations need to stop.  The following items need to be disabled:

1. Interrupts
2. SHA Accelerated MB command

If FW/HW is able to recover from the error, the outputs can be re-enabled as long as the error is reported to the user.

**Comment by JohnTraverAmd** [comment]
1. Interrupts are only sent to the SOC when FW decides to.
2. HW only sets the HW Fatal Error Wire.  This would not be a FIPS concern.

We don't have any HW autonomous output that is sent other than error.  No HW changes needed at this point.

**Comment by bharatpillilli** [comment]
@JohnTraverAmd to close this after FIPS discussions - no HW chanages needed
