### ISSUE TITLE
Make ECC logic in Caliptra optional

### ISSUE THREAD

**Issue by pkwidzin-amd** [chipsalliance/caliptra-rtl#99]
Given that memory is outside of Caliptra IP some integrators will prefer to handle ECC directly in wrapper on memory block provided by SoC. 
Request is to add configuration option to disable ECC logic and interfaces (or "ifdef" in RTL code).

**Comment by bharatpillilli** [comment]
There was something filed already on this by @JohnTraverAmd and I left the comment in there

"This is too late of an ask for an intrusive change. That said, I am open for AMD design reps to make the requisite changes and contribute into Caliptra RTL code database without causing impact to the 1p0 RTL milestone. If that is not possible, we move this to next generation."

Please check with AMD RTL development internally and make a decision
